[workspace]
members = [
    "programs/private-dao",
    "programs/privatedao-auction",
    "programs/zk-groth16-verifier",
    "providers/privatedao-zcash-orchard",
]
exclude = ["programs/private-dao/fuzz"]
resolver = "2"

[workspace.dependencies]
sha2 = "0.10"
anchor-lang = "1.0.3"
anchor-spl  = "1.0.3"
ephemeral-rollups-sdk = { version = "0.16.2", features = ["anchor", "access-control"] }
[patch.crates-io]
blake3 = { git = "https://github.com/BLAKE3-team/BLAKE3.git", tag = "1.5.5" }

[profile.release]
overflow-checks = true
