import type { MetadataRoute } from "next";

import { siteUrl } from "@/lib/site-brand";

export const dynamic = "force-static";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/llms.txt",
          "/llms-full.txt",
          "/ai.json",
          "/evidence.json",
          "/ownership.json",
          "/rights.txt",
          "/payroll/",
          "/treasury/",
          "/govern/",
          "/auctions/",
          "/proof-workflows/",
          "/products/",
          "/products/record-verification/",
          "/agents/",
          "/investors/",
          "/roadmap/",
          "/whitepaper/",
          "/token/",
          "/thesis/",
          "/about/",
          "/contact/",
          "/privacy/",
          "/terms/",
          "/legal/",
          "/verify/",
        ],
        disallow: [
          "/api/",
          "/documents/",
          "/viewer/",
          "/rooms/",
          "/services/",
          "/developers/",
          "/learn/",
          "/proof/",
          "/deck/",
          "/enterprise/",
          "/dashboard/",
          "/command-center/",
          "/analytics/",
          "/diagnostics/",
          "/judge",
          "/judges",
          "/judge-ai",
          "/gaming/",
          "/tracks/",
          "/android/",
          "/arena/",
          "/assistant/",
          "/awards/",
          "/benefit/",
          "/business-model/",
          "/colosseum/",
          "/community/",
          "/compliance/",
          "/custody/",
          "/dao-ui-template/",
          "/demo/",
          "/engage/",
          "/frontier/",
          "/futardio/",
          "/inteligence/",
          "/intelignce/",
          "/intelligence/",
          "/inttelignce/",
          "/live/",
          "/matrix/",
          "/network/",
          "/onboard/",
          "/payment-gate/",
          "/payment-template/",
          "/pilots/",
          "/pricing/",
          "/review/",
          "/reviewer/",
          "/runtime-template/",
          "/search/",
          "/settings/",
          "/start/",
          "/story/",
          "/submission/",
          "/trust/",
          "/try/",
          "/txline-settlement/",
          "/value/",
          "/versus/",
          "/wallet-template/",
          "/whiteprint/",
        ],
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: new URL(siteUrl).host,
  };
}
