export const SERVICES = Object.freeze([
  {
    id: "verify.basic",
    title: "Basic verification",
    price: 0,
    currency: "USDC",
    access: "free",
    input: "JSON evidence",
    output: "canonical digest and receipt",
  },
  {
    id: "verify.deep",
    title: "Deep verification",
    price: 0.25,
    currency: "USDC",
    access: "paid",
    input: "JSON evidence and rules",
    output: "verified receipt and checks",
  },
  {
    id: "token.intelligence",
    title: "Token intelligence",
    price: 0.03,
    currency: "USDC",
    access: "paid",
    input: "network and token identifier",
    output: "network, contract metadata and available on-chain evidence",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "risk.score",
    title: "Risk score",
    price: 0.02,
    currency: "USDC",
    access: "paid",
    input: "network and token identifier",
    output: "deterministic risk factors and evidence confidence",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "wallet.intelligence",
    title: "Wallet intelligence",
    price: 0.05,
    currency: "USDC",
    access: "paid",
    input: "network and wallet address",
    output: "bounded public-chain balance and activity evidence",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "contract.inspect",
    title: "Program inspection",
    price: 0.08,
    currency: "USDC",
    access: "paid",
    input: "Solana program",
    output: "account owner and executable-state evidence",
  },
  {
    id: "launch.check",
    title: "Launch check",
    price: 0.03,
    currency: "USDC",
    access: "paid",
    input: "Solana mint",
    output: "pre-decision launch evidence",
  },
  {
    id: "market.snapshot",
    title: "Market snapshot",
    price: 0.01,
    currency: "USDC",
    access: "paid",
    input: "network and token identifier",
    output: "on-chain token facts plus sourced market price and liquidity where available",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "research.asset",
    title: "AI asset research",
    price: 0.1,
    currency: "USDC",
    access: "paid",
    input: "network and asset identifier",
    output: "on-chain facts, labeled signals and evidence references",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "research.wallet",
    title: "Wallet behavior analysis",
    price: 0.1,
    currency: "USDC",
    access: "paid",
    input: "network and wallet address",
    output: "public balance, activity and asset evidence",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "contract.explain",
    title: "Smart contract explain",
    price: 0.1,
    currency: "USDC",
    access: "paid",
    input: "network and contract or program address",
    output: "deterministic bytecode, ownership and execution facts",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "transaction.explain",
    title: "Transaction explain before sign",
    price: 0.05,
    currency: "USDC",
    access: "paid",
    input: "network and transaction hash or signature",
    output: "pre-sign simulation or structured transaction facts and failure context",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "anomaly.detect",
    title: "On-chain anomaly detection",
    price: 0.15,
    currency: "USDC",
    access: "paid",
    input: "network and asset or wallet subject",
    output: "deterministic anomaly signals with evidence and no unsupported labels",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "agent.research.report",
    title: "Agent research report",
    price: 0.25,
    currency: "USDC",
    access: "paid",
    input: "network and asset or wallet subject",
    output: "structured facts, labeled signals, evidence digest and receipt",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "portfolio.intelligence",
    title: "Portfolio intelligence",
    price: 0.2,
    currency: "USDC",
    access: "paid",
    input: "network and up to 10 asset identifiers",
    output: "asset-by-asset facts, signals, failures and evidence digest",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "swap.quote",
    title: "Swap quote",
    price: 0.01,
    currency: "USDC",
    access: "paid",
    input: "Solana input mint, output mint and amount",
    output: "quote-only route, expected output, slippage and network cost",
    supportedNetworks: ["solana-mainnet-beta"],
  },
  {
    id: "transaction.simulate",
    title: "Transaction simulation",
    price: 0.02,
    currency: "USDC",
    access: "paid",
    input: "network and unsigned transaction",
    output: "simulation result, estimated gas and deterministic errors",
    supportedNetworks: ["solana-mainnet-beta", "ethereum-mainnet", "base-mainnet", "arbitrum-mainnet"],
  },
  {
    id: "decision.context",
    title: "Decision context",
    price: 0.1,
    currency: "USDC",
    access: "paid",
    input: "structured evidence",
    output: "deterministic evidence context",
  },
  {
    id: "receipt.verify",
    title: "Receipt verification",
    price: 0,
    currency: "USDC",
    access: "free",
    input: "receipt and expected hash",
    output: "receipt integrity result",
  },
  {
    id: "github.repository",
    title: "GitHub repository evidence",
    price: 0.08,
    currency: "USDC",
    access: "paid",
    input: "public GitHub repository URL",
    output: "repository metadata, provenance and release-relevant evidence",
  },
  {
    id: "forensics.trace",
    title: "Solana transaction trace",
    price: 0.75,
    currency: "USDC",
    access: "paid",
    input: "public Solana address",
    output: "read-only transaction summary",
  },
  {
    id: "agent.match",
    title: "Agent capability matching",
    price: 0.1,
    currency: "USDC",
    access: "paid",
    input: "capabilities and context",
    output: "ranked registry matches",
  },
  {
    id: "sponsored.discovery",
    title: "Sponsored machine discovery",
    price: 5,
    currency: "USDC",
    access: "paid",
    input: "verified Agent Card and targeting",
    output: "explicit sponsored placement",
  },
  {
    id: "intelligence.synthesize",
    title: "Evidence synthesis",
    price: 1,
    currency: "USDC",
    access: "paid",
    input: "structured evidence",
    output: "structured synthesis and receipt",
  },
]);

export function serviceById(id) {
  return SERVICES.find((service) => service.id === id) || null;
}
