export const SERVICES = Object.freeze([
  {
    id: "verify.basic",
    title: "Basic verification",
    price: 0,
    currency: "USDC",
    access: "free",
    input: "JSON evidence",
    output: "canonical digest and receipt",
  },
  {
    id: "verify.deep",
    title: "Deep verification",
    price: 0.25,
    currency: "USDC",
    access: "paid",
    input: "JSON evidence and rules",
    output: "verified receipt and checks",
  },
  {
    id: "token.intelligence",
    title: "Token intelligence",
    price: 0.03,
    currency: "USDC",
    access: "paid",
    input: "Solana mint",
    output: "mint, supply, holders and metadata evidence",
  },
  {
    id: "risk.score",
    title: "Risk score",
    price: 0.02,
    currency: "USDC",
    access: "paid",
    input: "Solana mint",
    output: "machine-readable risk factors and confidence",
  },
  {
    id: "wallet.intelligence",
    title: "Wallet intelligence",
    price: 0.05,
    currency: "USDC",
    access: "paid",
    input: "Solana wallet",
    output: "bounded public-chain activity evidence",
  },
  {
    id: "contract.inspect",
    title: "Program inspection",
    price: 0.08,
    currency: "USDC",
    access: "paid",
    input: "Solana program",
    output: "account owner and executable-state evidence",
  },
  {
    id: "launch.check",
    title: "Launch check",
    price: 0.03,
    currency: "USDC",
    access: "paid",
    input: "Solana mint",
    output: "pre-decision launch evidence",
  },
  {
    id: "market.snapshot",
    title: "Market snapshot",
    price: 0.01,
    currency: "USDC",
    access: "paid",
    input: "Solana mint",
    output: "current on-chain supply and holder snapshot",
  },
  {
    id: "decision.context",
    title: "Decision context",
    price: 0.1,
    currency: "USDC",
    access: "paid",
    input: "structured evidence",
    output: "deterministic evidence context",
  },
  {
    id: "receipt.verify",
    title: "Receipt verification",
    price: 0,
    currency: "USDC",
    access: "free",
    input: "receipt and expected hash",
    output: "receipt integrity result",
  },
  {
    id: "forensics.trace",
    title: "Solana transaction trace",
    price: 0.75,
    currency: "USDC",
    access: "paid",
    input: "public Solana address",
    output: "read-only transaction summary",
  },
  {
    id: "agent.match",
    title: "Agent capability matching",
    price: 0.1,
    currency: "USDC",
    access: "paid",
    input: "capabilities and context",
    output: "ranked registry matches",
  },
  {
    id: "sponsored.discovery",
    title: "Sponsored machine discovery",
    price: 5,
    currency: "USDC",
    access: "paid",
    input: "verified Agent Card and targeting",
    output: "explicit sponsored placement",
  },
  {
    id: "intelligence.synthesize",
    title: "Evidence synthesis",
    price: 1,
    currency: "USDC",
    access: "paid",
    input: "structured evidence",
    output: "structured synthesis and receipt",
  },
]);

export function serviceById(id) {
  return SERVICES.find((service) => service.id === id) || null;
}
