const {
  redeemPromoCode,
  referralCodeForTelegramId,
  parseReferralPayload,
  applyReferralStart,
  DEFAULT_PROMO_DAYS,
  REFERRAL_REWARD_DAYS,
  REFERRAL_WELCOME_DAYS,
} = require('../billing/fees');
const { getBotWallet, getOrCreateUser } = require('../db/supabase');

let cachedBotUsername = null;

async function getBotUsername(bot) {
  if (cachedBotUsername) return cachedBotUsername;
  if (process.env.TELEGRAM_BOT_USERNAME) {
    cachedBotUsername = process.env.TELEGRAM_BOT_USERNAME.replace(/^@/, '');
    return cachedBotUsername;
  }
  const me = await bot.getMe();
  cachedBotUsername = me.username;
  return cachedBotUsername;
}

async function handleStartPayload(bot, msg, payload) {
  await getOrCreateUser(msg.from.id, msg.from.username || null).catch(() => null);
  if (String(payload || '').trim().toLowerCase() === 'community') {
    await bot.sendMessage(msg.chat.id,
      `👥 *Community mode*\n\nTrading stays in private chat.\nUse the buttons to continue securely.`
    );
    await bot.sendMessage(msg.chat.id,
      `✅ *Verified*\n\nOfficial bot: https://t.me/PrivateDAO0_bot\nWebsite: https://privatedao.org\nX: https://x.com/PrivateDAOOS\nGitHub: https://github.com/PrivateDAO`
    );
    return { applied: true, source: 'community' };
  }
  const inviterTelegramId = parseReferralPayload(payload);
  if (!inviterTelegramId) return null;
  const result = await applyReferralStart(msg.from.id, inviterTelegramId);
  if (!result.applied) return result;
  await bot.sendMessage(msg.chat.id,
    `🎁 *Referral activated*\n\n` +
    `You received ${REFERRAL_WELCOME_DAYS} access days.\n` +
    `Your inviter received ${REFERRAL_REWARD_DAYS} bonus days.`
  );
  return result;
}

async function handlePromo(bot, msg, raw = '') {
  const chatId = msg.chat.id;
  const code = String(raw || '').trim();
  if (!code) {
    return bot.sendMessage(chatId,
      `🎁 *Promo Code*\n\n` +
      `Send:\n` +
      `\`/redeem YOURCODE\`\n\n` +
      `Promo access is code-based and bound to your execution wallet. Codes are generated by the owner.`
    );
  }

  try {
    const botWallet = await getBotWallet(msg.from.id).catch(() => null);
    if (!botWallet) {
      return bot.sendMessage(chatId,
        `Create your execution wallet first with /deposit, then redeem the promo code so it is bound to one wallet only.`
      );
    }

    const result = await redeemPromoCode(msg.from.id, msg.from.username || null, code, botWallet.public_key);
    const status = result.alreadyRedeemed ? 'already active' : 'activated';
    return bot.sendMessage(chatId,
      `🎁 *Promo ${status}*\n\n` +
      `Code: \`${result.code}\`\n` +
      `Access: ${result.freeDays} days\n` +
      `Valid until: ${result.expiresAt.toISOString()}\n\n` +
      `Trading still uses the normal PnL fee policy: no realized profit means no service fee.`
    );
  } catch (err) {
    return bot.sendMessage(chatId, `Promo failed: ${err.message}`);
  }
}

async function handleReferral(bot, msg) {
  const username = await getBotUsername(bot);
  const code = referralCodeForTelegramId(msg.from.id);
  const link = `https://t.me/${username}?start=${code}`;
  return bot.sendMessage(msg.chat.id,
    `🔗 *Your Invite Link*\n\n` +
    `${link}\n\n` +
    `Reward: ${REFERRAL_REWARD_DAYS} access days for you.\n` +
    `Welcome: ${REFERRAL_WELCOME_DAYS} access days for your invited trader.`
  );
}

async function handleFreeAccess(bot, msg) {
  return bot.sendMessage(msg.chat.id,
    `🔓 *Redeem Access*\n\n` +
      `Access is code-based and bound to one execution wallet.\n\n` +
      `Redeem a code like:\n\`/redeem YOURCODE\`\n` +
      `Codes are issued by the owner and are one-time use.\n\n` +
      `Invite link:\n\`/referral\``
  );
}

module.exports = {
  handleStartPayload,
  handlePromo,
  handleReferral,
  handleFreeAccess,
};
