import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  buildNativeCapabilityRegistry,
  findApplicationBinding,
  NETWORK_MATRIX,
  PAYMENT_RAIL_CATALOG,
  PRODUCT_CATALOG,
} from "../packages/privatedao-runtime/src/index.js";

async function main() {
  const root = process.cwd();
  const nativeCapabilities = buildNativeCapabilityRegistry();
  const outputPath = process.env.WEB_RUNTIME_CATALOG_OUTPUT
    ? path.resolve(root, process.env.WEB_RUNTIME_CATALOG_OUTPUT)
    : path.join(root, "apps/web/src/lib/runtime-catalog.generated.ts");

  const payload = {
    generatedFrom: "packages/privatedao-runtime/src/catalog.ts and networks.ts",
    products: PRODUCT_CATALOG.map((product) => ({
      id: product.id,
      name: product.name,
      availability: product.availability,
      networks: [...product.networks],
      capabilities: product.capabilities.map((capability) => ({
        id: capability.id,
        version: capability.version,
        requiresSignature: capability.requiresSignature,
        supportsAsync: capability.supportsAsync,
        receiptSchema: capability.receiptSchema,
        applicationBindings: capability.networks.map((network) => {
            const binding = findApplicationBinding(product.id, capability.id, network);
            const evidence = nativeCapabilities.find(
              (entry) => entry.product === product.id && entry.capability === capability.id && entry.network === network,
            );
            if (!evidence) throw new Error(`Missing native capability evidence row for ${product.id}/${capability.id}/${network}`);
            return {
              network,
              mode: binding.mode,
              entrypoint: binding.entrypoint ?? null,
              method: binding.method ?? null,
              note: binding.note,
              evidenceStatus: evidence.status,
              evidence: evidence.evidence,
              supportsExecution: evidence.supportsExecution,
              supportsProof: evidence.supportsProof,
              supportsReceipt: evidence.supportsReceipt,
              supportsReconciliation: evidence.supportsReconciliation,
              supportedAssets: [...evidence.supportedAssets],
              provider: evidence.provider,
            };
        }),
        networkAvailability: NETWORK_MATRIX.map((network) => {
          const declared = capability.networks.includes(network.id) && product.networks.includes(network.id);
          const binding = declared ? findApplicationBinding(product.id, capability.id, network.id) : null;
          const evidence = nativeCapabilities.find(
            (entry) => entry.product === product.id && entry.capability === capability.id && entry.network === network.id,
          );
          if (!evidence) throw new Error(`Missing native capability evidence row for ${product.id}/${capability.id}/${network.id}`);
          const evidenceBacked = Boolean(
            binding?.mode === "kernel-gateway"
              && evidence.supportsExecution
              && ["devnet_verified", "testnet_verified", "mainnet_live"].includes(evidence.status),
          );
          return {
            network: network.id,
            stage: network.stage,
            environment: network.environment,
            chainId: network.chainId ?? null,
            declared,
            mode: binding?.mode ?? "unbound",
            evidenceStatus: evidence.status,
            evidence: evidence.evidence,
            executable: evidenceBacked,
            supportsProof: evidence.supportsProof,
            supportsReceipt: evidence.supportsReceipt,
            supportsReconciliation: evidence.supportsReconciliation,
            supportedAssets: [...evidence.supportedAssets],
            provider: evidence.provider,
          };
        }),
      })),
    })),
    networks: NETWORK_MATRIX.map((network) => ({
      id: network.id,
      label: network.label,
      family: network.family,
      stage: network.stage,
      environment: network.environment,
      chainId: network.chainId,
      adapterId: network.adapterId,
    })),
    paymentRails: PAYMENT_RAIL_CATALOG.map((rail) => ({
      id: rail.id,
      label: rail.label,
      purpose: rail.purpose,
      sourceNetwork: rail.sourceNetwork,
      destinationNetwork: rail.destinationNetwork,
      asset: rail.asset,
      privacy: rail.privacy,
      supportsBatch: rail.supportsBatch,
      status: rail.status,
      evidence: [...rail.evidence],
    })),
  };

  const contents = `// Generated by scripts/build-web-runtime-catalog.ts. Do not edit by hand.\n\nexport const runtimeCatalog = ${JSON.stringify(payload, null, 2)} as const;\n`;

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, contents, "utf8");
  console.log(`wrote ${path.relative(root, outputPath)}`);
}

void main();
