import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { NETWORK_MATRIX, PRODUCT_CATALOG } from "../packages/privatedao-runtime/src/index.js";

async function main() {
  const root = process.cwd();
  const outputPath = process.env.WEB_RUNTIME_CATALOG_OUTPUT
    ? path.resolve(root, process.env.WEB_RUNTIME_CATALOG_OUTPUT)
    : path.join(root, "apps/web/src/lib/runtime-catalog.generated.ts");

  const payload = {
    generatedFrom: "packages/privatedao-runtime/src/catalog.ts and networks.ts",
    products: PRODUCT_CATALOG.map((product) => ({
      id: product.id,
      name: product.name,
      availability: product.availability,
      networks: [...product.networks],
      capabilities: product.capabilities.map((capability) => ({
        id: capability.id,
        version: capability.version,
        requiresSignature: capability.requiresSignature,
        supportsAsync: capability.supportsAsync,
        receiptSchema: capability.receiptSchema,
      })),
    })),
    networks: NETWORK_MATRIX.map((network) => ({
      id: network.id,
      label: network.label,
      family: network.family,
      stage: network.stage,
      environment: network.environment,
      chainId: network.chainId,
      adapterId: network.adapterId,
    })),
  };

  const contents = `// Generated by scripts/build-web-runtime-catalog.ts. Do not edit by hand.\n\nexport const runtimeCatalog = ${JSON.stringify(payload, null, 2)} as const;\n`;

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, contents, "utf8");
  console.log(`wrote ${path.relative(root, outputPath)}`);
}

void main();
