#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="dist/reviewer-bundle"
ARCHIVE="dist/reviewer-bundle.tar.gz"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/docs"
mkdir -p "$OUT_DIR/docs/assets"

cp README.md "$OUT_DIR/"
cp docs/reviewer-fast-path.md "$OUT_DIR/docs/"
cp docs/security-review.md "$OUT_DIR/docs/"
cp docs/threat-model.md "$OUT_DIR/docs/"
cp docs/security-coverage-map.md "$OUT_DIR/docs/"
cp docs/failure-modes.md "$OUT_DIR/docs/"
cp docs/replay-analysis.md "$OUT_DIR/docs/"
cp docs/protocol-spec.md "$OUT_DIR/docs/"
cp docs/security-architecture.md "$OUT_DIR/docs/"
cp docs/security-guarantees.md "$OUT_DIR/docs/"
cp docs/protocol-maturity.md "$OUT_DIR/docs/"
cp docs/independent-verification.md "$OUT_DIR/docs/"
cp docs/verification-gates.md "$OUT_DIR/docs/"
cp docs/artifact-freshness.md "$OUT_DIR/docs/"
cp docs/review-automation.md "$OUT_DIR/docs/"
cp docs/live-proof.md "$OUT_DIR/docs/"
cp docs/test-wallet-live-proof.generated.md "$OUT_DIR/docs/"
cp docs/test-wallet-live-proof.generated.json "$OUT_DIR/docs/"
cp docs/governance-hardening-v3.md "$OUT_DIR/docs/"
cp docs/settlement-hardening-v3.md "$OUT_DIR/docs/"
cp docs/test-wallet-live-proof-v3.generated.md "$OUT_DIR/docs/"
cp docs/test-wallet-live-proof-v3.generated.json "$OUT_DIR/docs/"
cp docs/token.md "$OUT_DIR/docs/"
cp docs/pdao-token.md "$OUT_DIR/docs/"
cp docs/consumer-readiness.md "$OUT_DIR/docs/"
cp docs/consumer-user-flows.md "$OUT_DIR/docs/"
cp docs/launch-growth-plan.md "$OUT_DIR/docs/"
cp docs/pdao-attestation.generated.json "$OUT_DIR/docs/"
cp docs/assets/pdao-token.json "$OUT_DIR/docs/assets/"
cp docs/assets/logo.png "$OUT_DIR/docs/assets/"
cp docs/fair-voting.md "$OUT_DIR/docs/"
cp docs/wallet-runtime.md "$OUT_DIR/docs/"
cp docs/runtime/real-device.md "$OUT_DIR/docs/"
cp docs/runtime/real-device-captures.json "$OUT_DIR/docs/"
cp docs/runtime/real-device.generated.md "$OUT_DIR/docs/"
cp docs/runtime/real-device.generated.json "$OUT_DIR/docs/"
cp docs/runtime/browser-wallet.md "$OUT_DIR/docs/"
cp docs/runtime/browser-wallet-captures.json "$OUT_DIR/docs/"
cp docs/runtime/browser-wallet.generated.md "$OUT_DIR/docs/"
cp docs/runtime/browser-wallet.generated.json "$OUT_DIR/docs/"
cp docs/operational-evidence.generated.md "$OUT_DIR/docs/"
cp docs/operational-evidence.generated.json "$OUT_DIR/docs/"
cp docs/go-live-criteria.md "$OUT_DIR/docs/"
cp docs/operational-drillbook.md "$OUT_DIR/docs/"
cp docs/release-ceremony.md "$OUT_DIR/docs/"
cp docs/release-ceremony-attestation.generated.md "$OUT_DIR/docs/"
cp docs/release-ceremony-attestation.generated.json "$OUT_DIR/docs/"
cp docs/runtime-attestation.generated.json "$OUT_DIR/docs/"
cp docs/runtime-evidence.generated.md "$OUT_DIR/docs/"
cp docs/runtime-evidence.generated.json "$OUT_DIR/docs/"
cp docs/governance-runtime-proof.generated.md "$OUT_DIR/docs/"
cp docs/governance-runtime-proof.generated.json "$OUT_DIR/docs/"
cp docs/release-drill.generated.md "$OUT_DIR/docs/"
cp docs/release-drill.generated.json "$OUT_DIR/docs/"
cp docs/zk-provenance.md "$OUT_DIR/docs/"
cp docs/zk-transcript.generated.md "$OUT_DIR/docs/"
cp docs/zk-attestation.generated.json "$OUT_DIR/docs/"
cp docs/devnet-release-manifest.md "$OUT_DIR/docs/"
cp docs/proof-registry.json "$OUT_DIR/docs/"
cp docs/audit-packet.generated.md "$OUT_DIR/docs/"
cp docs/review-attestation.generated.json "$OUT_DIR/docs/"
cp docs/mainnet-readiness.generated.md "$OUT_DIR/docs/"
cp docs/deployment-attestation.generated.json "$OUT_DIR/docs/"
cp docs/go-live-attestation.generated.json "$OUT_DIR/docs/"
cp docs/reviewer-surface-map.md "$OUT_DIR/docs/"
cp docs/submission-dossier.md "$OUT_DIR/docs/"
cp docs/audit-handoff.md "$OUT_DIR/docs/"
cp docs/external-audit-engagement.md "$OUT_DIR/docs/"
cp docs/production-custody-ceremony.md "$OUT_DIR/docs/"
cp docs/operator-checklist.md "$OUT_DIR/docs/"
cp docs/pilot-onboarding-playbook.md "$OUT_DIR/docs/"
cp docs/risk-register.md "$OUT_DIR/docs/"
cp docs/mainnet-readiness.md "$OUT_DIR/docs/"
cp docs/production-operations.md "$OUT_DIR/docs/"
cp docs/launch-trust-packet.generated.md "$OUT_DIR/docs/"
cp docs/launch-trust-packet.generated.json "$OUT_DIR/docs/"
cp docs/treasury-reviewer-packet.generated.md "$OUT_DIR/docs/"
cp docs/treasury-reviewer-packet.generated.json "$OUT_DIR/docs/"
cp docs/reviewer-telemetry-packet.generated.md "$OUT_DIR/docs/"
cp docs/reviewer-telemetry-packet.generated.json "$OUT_DIR/docs/"

tar -czf "$ARCHIVE" -C dist reviewer-bundle

echo "Wrote review bundle: $ARCHIVE"
