import fs from "fs";
import path from "path";

const FRONTEND = path.resolve("docs/index.html");

function main() {
  const body = fs.readFileSync(FRONTEND, "utf8");

  const requiredFragments = [
    "Zero-Knowledge Layer Live",
    "Companion proofs + zk_enforced path",
    "vote-validity, delegation-authorization, and tally-integrity proof layers",
    "DELEGATION LAYER",
    "TALLY LAYER",
    "zk-stack.md",
    "Connect a Solana wallet such as Phantom, Solflare, or Backpack on Devnet.",
    "window.backpack?.solana",
    "window.solflare?.solflare",
    "walletProviderName",
    "waitForWalletPublicKey",
    "selectedAddress",
    "accountsArray",
    "custom-cursor-enabled",
    "requestAnimationFrame(renderCursor)",
    "verify:all",
    "zk-layer.md",
    "zk-capability-matrix.md",
    "CAPABILITY MATRIX",
    "PER-LAYER REVIEW PATH",
    "🔒 ZK Companion Layer",
    "1st Place · Superteam Poland",
    "Zero-Knowledge Protection",
    "Groth16 zk-SNARK companion proofs",
    "ZK Layer",
    "zk_enforced hardening",
    "proposal-bound proof anchors are now recorded on-chain",
    "Proof generation and verification remain additive and off-chain",
    "verify:zk-docs",
    "zk-provenance.md",
    "zk-transcript.generated.md",
    "zk-attestation.generated.json",
    "verify:zk-transcript",
    "verify:zk-attestation",
    "verify:zk-consistency",
    "verify:zk-negative",
    "Artifact Integrity",
    "cryptographic-integrity.md",
    "cryptographic-manifest.generated.json",
    "PDAO",
    "DeAura",
    "Governance Voting Token",
    "Community treasury app",
    "Confidential payroll and bonus plans",
    "PrivateDAO Governance Token (PDAO)",
    "Enables proposal participation",
    "Supports voting authority",
    "Aligns treasury governance",
    "Prevents governance spam",
    "Anchors long-term ecosystem participation",
    "token.md",
    "pdao-token.md",
    "pdao-attestation.generated.json",
    "assets/pdao-token.json",
    "AZUkprJDfJPgAp7L4z3TpCV3KHqLiA8RjHAVhK9HCvDt",
    "1,000,000 PDAO",
    "Token-2022",
    "PROGRAM BOUNDARY",
    "verify:cryptographic-manifest",
    "SUPPORTED DEVNET WALLETS",
    "Phantom",
    "Solflare",
    "Backpack",
    "Glow",
    "toggleWalletPanel",
    "Security Evidence",
    "ATTESTATION",
    "Open zk attestation",
    "ZK PROOF ANCHORS",
    "Open Vote Anchor",
    "Open Delegation Anchor",
    "Open Tally Anchor",
    "TRUTH-ALIGNED",
    "The raw commitment hash binds vote, salt, proposal key, and voter key.",
    "proposal account stays rent-safe",
    "Save the salt yourself; the browser does not persist it.",
    "page-docs",
    "Interactive Review Document",
    "docViewerContent",
    "copyDocViewerLink",
    "renderMarkdownDocument",
    "renderJsonDocument",
    "isInteractiveDocLink",
    "Open Raw File",
    "openDocument('zk-layer.md','ZK Layer',this)",
    "openDocument('android-native.md','Android Native',this)",
    "page-diagnostics",
    "Wallet Diagnostics",
    "updateDiagnostics()",
    "copyDiagnosticsSnapshot",
    "diagSnapshotOutput",
    "mainnet-readiness.generated.md",
    "mainnet-acceptance-matrix.generated.md",
    "mainnet-proof-package.generated.md",
    "deployment-attestation.generated.json",
    "go-live-criteria.md",
    "operational-drillbook.md",
    "runtime-attestation.generated.json",
    "runtime-evidence.generated.md",
    "runtime/real-device.md",
    "runtime/real-device.generated.md",
    "magicblock/runtime-evidence.md",
    "magicblock/runtime.generated.md",
    "zk/enforced-runtime-evidence.md",
    "zk/enforced-runtime.generated.md",
    "zk/enforced-operator-flow.md",
    "zk/external-closure.generated.md",
    "go-live-attestation.generated.json",
    "Fair Voting Model",
    "Wallet Runtime",
    "Real-Device Runtime QA",
    "Real-Device Runtime Evidence",
    "MagicBlock Runtime Evidence",
    "ZK-Enforced Runtime Evidence",
    "ZK External Closure",
    "Competitive Position",
    "ANCHOR EVENTS",
    "SETTLEMENT EVIDENCE",
    "CONFIDENTIAL EXECUTION BOUNDARY",
    "build:colosseum-competitive",
    "verify:colosseum-competitive",
    "Runtime Evidence",
    "Operational Evidence",
    "Devnet Scale Profiles",
    "Consumer Readiness",
    "Consumer User Flows",
    "Launch And Growth Plan",
    "Investor / Competition Deck",
    "Production Simulation And Startup Packs",
    "Production Simulation DAO",
    "Use Case Packs",
    "Grant Committee Pack",
    "Fund Governance Pack",
    "Gaming DAO Pack",
    "Enterprise DAO Pack",
    "Operator Guide",
    "Trust Package",
    "Migration Story",
    "Pilot SLA",
    "Pricing Model",
    "Pilot Program",
    "Autonomous Executor ↗",
    "Executor Packet ↗",
    "AUTONOMOUS EXECUTOR",
    "AUTONOMOUS EXECUTOR PACK",
    "governance-controlled execution-agent path for the Zerion track",
    "a Zerion CLI fork becomes the wallet and execution engine",
    "Open Autonomous Executor",
    "Open Executor Packet",
    "PrivateDAO Autonomous Executor",
    "Service Catalog",
    "API, operator, and migration services",
    "HOSTED READ API",
    "REVIEW EXPORTS",
    "REALMS MIGRATION SERVICE",
    "PILOT AND OPERATOR SUPPORT",
    "BUYER PATH",
    "Pilot first, not vague enterprise theater",
    "COMMERCIAL PACKS",
    "Four ways to buy the product surface",
    "PILOT PACKAGE",
    "HOSTED READ API + OPS",
    "CONFIDENTIAL OPERATIONS PREMIUM",
    "ENTERPRISE GOVERNANCE RETAINER",
    "Open Pilot Program",
    "Open Pricing Model",
    "BUYER JOURNEY",
    "WHO THIS IS FOR",
    "WHY NOT REALMS OR SQUADS ALONE",
    "FIRST 30 DAYS",
    "LIVE NOW VS PENDING-EXTERNAL",
    "Organizations hurt by public signaling",
    "PrivateDAO is the privacy and execution layer on top of treasury discipline",
    "Pilot, prove, train, then decide",
    "Strong live Devnet product, honest mainnet boundary",
    "TRUST THE BOUNDARY",
    "ACT LIKE A PRODUCT",
    "Open Product Packs",
    "Open Buyer Surface",
    "COMMERCIAL CHECKOUT RAIL",
    "WEEK 1",
    "WEEK 2",
    "WEEK 3",
    "WEEK 4",
    "REQUEST PILOT PACKET",
    "Copy Pilot Packet",
    "copyPilotRequestPacket",
    "Pilot packet copied.",
    "Judge View",
    "Buyer View",
    "Operator View",
    "openJudgeQuickView",
    "openBuyerQuickView",
    "openOperatorQuickView",
    "HERO_PERSONAS",
    "setHeroPersona",
    "PROPOSAL_PACK_SUMMARIES",
    "updateSelectedPackSummary",
    "openSelectedPackDocument",
    "selectedPackBadge",
    "selectedPackTitle",
    "selectedPackBestFor",
    "selectedPackBuyerPath",
    "selectedPackOffer",
    "selectedPackTechList",
    "selectedPackOutcomeList",
    "selectedPackProof",
    "proposalExperienceGrid",
    "BUYER STORY",
    "OPERATOR NEXT STEP",
    "JUDGE PATH",
    "Selected proposal packet copied.",
    "LIVE SUCCESS PROOF",
    "Real Devnet treasury execution already completed",
    "Latest Live Proof",
    "REVIEWER PACKET",
    "50 wallets, 212 attempts, 3 on-chain ZK anchors",
    "BOUNDARY CHECK",
    "Live now versus pending-external stays explicit",
    "Buyer surface selected. Start from pricing, pilot packet, and trust boundary.",
    "Operator surface opened. Start from the command center and active proposal flow.",
    "Judge surface selected. Start from the proof strip, judge link, and reviewer packets.",
    "PRIVATE GOVERNANCE · COMMERCIAL PACKS · SOLANA DEVNET LIVE",
    "OPERATE",
    "THE",
    "LIFECYCLE.",
    "STANDARD GRANT PACK",
    "Open Pack Doc",
    "Copy Service Packet",
    "Compare Plans",
    "API Surface",
    "No pack document configured for this preset.",
    "Commercial Decision Surface",
    "DECISION LAYER",
    "COMPARE PLANS",
    "API + OPS",
    "LIVE BOUNDARY",
    "Commercial compare surface opened. Start from the pack fit, then move into pricing or the pilot packet.",
    "API and operations surface opened. Use this for hosted read path, reviewer exports, and migration support.",
    "Live boundary surface opened. Review live-now versus pending-external before promising a launch path.",
    "copyServiceCatalogPacket",
    "Service packet copied.",
    "openCommercialCompare",
    "openCommercialApiSurface",
    "openLiveBoundaryMatrix",
    "copySelectedProposalCommercialPacket",
    "STOREFRONT",
    "Choose the operating pack that matches the organization you serve.",
    "PRODUCT-FIRST ENTRY",
    "CHECKOUT-LIKE ONBOARDING",
    "Start like a product operator, not like a protocol archaeologist.",
    "Choose product pack",
    "Create and fund DAO",
    "Launch proposal",
    "Private vote and execute",
    "storefrontPackState",
    "storefrontDaoState",
    "storefrontProposalState",
    "storefrontVoteState",
    "scrollToStorefrontShelf",
    "openStorefrontFundingStep",
    "openStorefrontProposalLaunch",
    "updateStorefrontOnboardingRail",
    "storefrontShelfStatus",
    "storefrontShelfCopy",
    "storefrontBestForTitle",
    "storefrontBestForCopy",
    "storefrontWhyPackTitle",
    "storefrontWhyPackCopy",
    "storefrontTechTitle",
    "storefrontTechList",
    "storefrontCtaTitle",
    "storefrontCtaCopy",
    "STOREFRONT_PROFILES_BY_PRESET",
    "setStorefrontProfileByPreset",
    "hero-tech-grid",
    "Solana + Anchor",
    "ZK Layer",
    "REFHE",
    "MagicBlock",
    "RPC Fast",
    "Realms + Android",
    "heroPrimaryCtaLabel",
    "heroSecondaryCtaLabel",
    "Start with the pack that matches the organization you operate.",
    "Best for grant committees that need private approvals and clean execution steps.",
    "TECHNOLOGY FIT",
    "Launch the DAO bootstrap, treasury funding, and proposal builder with the right defaults already loaded.",
    "GRANT COMMITTEE PACK",
    "FUND GOVERNANCE PACK",
    "GAMING DAO PACK",
    "ENTERPRISE DAO PACK",
    "Migrate from Realms",
    "REALMS MIGRATION PACKS",
    "Start from the migration profile that matches the organization you are moving.",
    "COMMUNITY TREASURY",
    "GRANT PROGRAM",
    "FUND GOVERNANCE",
    "ENTERPRISE OPS",
    "migrationPresetStatus",
    "NEXT STEP GUIDE",
    "What to do immediately after migration.",
    "migrationAdvisorCopy",
    "migrationAdvisorPill",
    "migrationFirstFlowState",
    "migrationFitState",
    "migrationPrivacyState",
    "migrationPackDocState",
    "applyMigrationPreset",
    "syncMigrationCommand",
    "copyMigrationCommand",
    "openMigrationPackDocument",
    "Start a DAO",
    "Start Private Payout",
    "Explore Services",
    "openStorefrontDaoFlow",
    "openRealmsMigrationStorefront",
    "openServiceCatalog",
    "startUseCasePack",
    "REAL DEMO VIDEO",
    "Demo Video Brief",
    "assets/private-dao-demo-flow.mp4",
    "investor-pitch-deck.md",
    "Confidential Treasury Operations",
    "CONFIDENTIAL TREASURY COMMAND CENTER",
    "One guided path from private approval to evidence-gated execution.",
    "ACTIVE FLOW CONTEXT",
    "Create proposal",
    "Commit vote",
    "Reveal and finalize",
    "Execute treasury",
    "Open Builder",
    "Open Commit",
    "Open Reveal",
    "Open Execute",
    "ZK companion layer",
    "Encrypted evaluation",
    "Private token corridor",
    "Read-node reliability",
    "frontier-guided-flow.md",
    "Open Frontier Flow",
    "FRONTIER BUILDER ADVISOR",
    "Choose the right activation path before signing.",
    "SMART PRESETS",
    "Start from a proposal template that already matches the operating path.",
    "proposalBuilderPresetStatus",
    "STANDARD TREASURY GRANT",
    "CONFIDENTIAL PAYROLL",
    "CONFIDENTIAL BONUS",
    "PRIVATE TOKEN DISTRIBUTION",
    "applyProposalBuilderPreset",
    "proposalBuilderAdvisorCopy",
    "proposalBuilderAdvisorPill",
    "proposalAdvisorZkState",
    "proposalAdvisorRefheState",
    "proposalAdvisorMagicBlockState",
    "proposalAdvisorRpcState",
    "updateProposalBuilderAdvisor",
    "setProposalAdvisorState",
    "RPC FAST / READ NODE",
    "Backend-indexed RPC Fast-oriented read path for proposal, runtime, and ops visibility",
    "Start Guided Flow",
    "copyConfidentialTreasuryEvidencePacket",
    "openConfidentialTreasuryWizard",
    "openTreasuryCommandCommit",
    "openTreasuryCommandReveal",
    "openTreasuryCommandExecute",
    "updateConfidentialTreasuryCommandCenter",
    "Paste real hashes before signing.",
    "Encrypted payroll and bonus approvals",
    "REFHE Protocol",
    "REFHE Operator Flow",
    "REFHE ENVELOPE",
    "REFHE READINESS",
    "REFHE PROTOCOL",
    "REFHE MODEL URI",
    "REFHE POLICY HASH (32-BYTE HEX)",
    "REFHE INPUT HASH (32-BYTE HEX)",
    "REFHE EVALUATION KEY HASH (32-BYTE HEX)",
    "refhe-protocol.md",
    "refhe-operator-flow.md",
    "This confidential payout is bound to a REFHE envelope that is not settled yet.",
    "This confidential payout is bound to a REFHE envelope",
    "READ PATH",
    "REFHE BACKEND",
    "350-WALLET PROFILE",
    "READ NODE METRICS",
    "Backend Indexer",
    "read-node/indexer.md",
    "read-node/same-domain-deploy.md",
    "rpc-architecture.md",
    "backend-operator-flow.md",
    "read-node/snapshot.generated.md",
    "read-node/ops.generated.md",
    "Open generated read-node snapshot",
    "Open generated ops snapshot",
    "Open Read Node Snapshot",
    "Open Ops Snapshot",
    "Open same-domain deploy path",
    "Open Same-Domain Deploy",
    "READ NODE / INDEXER",
    "OPS SNAPSHOT",
    "Open read-node and indexer path",
    "SAME-DOMAIN DEPLOY",
    "confidential-payments.md",
    "confidential-payroll-flow.md",
    "confidential-payments-diagram.md",
    "Wallet Compatibility Matrix",
    "Devnet Canary",
    "Cryptographic Posture",
    "Artifact Freshness",
    "Supply-Chain Attestation",
    "Release Ceremony",
    "Release Drill",
    "Review Automation",
    "Go-Live Criteria",
    "Operational Drillbook",
    "External Readiness Intake",
    "Runtime Attestation",
    "Go-Live Attestation",
    "Mainnet Acceptance Matrix",
    "Mainnet Proof Package",
    "Mainnet Blockers",
    "FRONTIER INTEGRATIONS",
    "LIVE DEVNET PROOF",
    "frontier-integrations.generated.md",
    "Open Frontier Integrations",
    "Multisig Setup Intake",
    "Launch Ops Checklist",
    "Monitoring Alert Rules",
    "Wallet E2E Test Plan",
    "Launch Trust Packet",
    "Production Custody Ceremony",
    "External Audit Engagement",
    "Pilot Onboarding Playbook",
    "50 wallets · 212 attempts · 32 expected rejects · 3 ZK anchors",
    "STARTUP LAUNCH OPS",
    "TRACKED, NOT CLEARED",
    "wallet-compatibility-matrix.generated.md",
    "devnet-canary.generated.md",
    "cryptographic-posture.md",
    "supply-chain-attestation.generated.md",
    "release-ceremony-attestation.generated.md",
    "release-drill.generated.md",
    "devnet-scale-profiles.md",
    "artifact-freshness.md",
    "review-automation.md",
    "mainnet-blockers.md",
    "multisig-setup-intake.md",
    "launch-ops-checklist.md",
    "monitoring-alert-rules.md",
    "wallet-e2e-test-plan.md",
    "Open Runtime Evidence",
    "Open Real-Device Runtime",
    "Open Operational Evidence",
    "Open Acceptance Matrix",
    "Open Mainnet Proof Package",
    "domain-mirror.md",
    "Mirror Deployment",
    "Open Devnet Scale Profiles",
    "Open Wallet Matrix",
    "Open Devnet Canary",
    "Open Release Drill",
    "Open Artifact Freshness",
    "Open External Readiness Intake",
    "Open Review Automation",
    "RPC HEALTH",
    "SUPPORTED PROVIDERS",
    "BROWSER CAPABILITIES",
    "LIVE RUNTIME",
    "Wallet connected but did not expose a public key in time.",
    "assets/vendor/solana-web3.iife.min.js",
  ];

  for (const fragment of requiredFragments) {
    assertContains(body, fragment, `frontend surface is missing required fragment: ${fragment}`);
  }

  assertNotContains(body, "setInterval(() => {\n  rx +=", "frontend still uses the old interval-based cursor loop");
  assertNotContains(body, "Tracks, sponsors,<br>and ecosystem fit.", "low-signal hackathon context section still exists on the main surface");
  assertNotContains(body, "Install Phantom or Solflare to sign transactions.", "frontend still shows the outdated wallet-install guidance");
  assertNotContains(body, "https://unpkg.com/@solana/web3.js", "frontend must not depend on the unpkg-hosted Solana web3 bundle");
  assertNotContains(body, "https://fonts.googleapis.com", "frontend must not depend on Google Fonts");
  assertNotContains(body, "50 wallets · 223 tx · 50 adversarial checks", "frontend still shows stale Devnet rehearsal totals");
  assertNotContains(body, "localStorage.setItem", "frontend must not persist sensitive governance state in localStorage");
  assertNotContains(body, "localStorage.getItem", "frontend must not read persisted localStorage vote secrets");
  assertNotContains(body, "sessionStorage.setItem", "frontend must not persist sensitive governance state in sessionStorage");
  assertNotContains(body, "sessionStorage.getItem", "frontend must not read persisted sessionStorage vote secrets");

  console.log("Frontend surface verification: PASS");
}

function assertContains(body: string, fragment: string, message: string) {
  if (!body.includes(fragment)) {
    throw new Error(message);
  }
}

function assertNotContains(body: string, fragment: string, message: string) {
  if (body.includes(fragment)) {
    throw new Error(message);
  }
}

main();
