import fs from "fs";
import path from "path";

import { getTrackReviewerPacketPublicLabel, getTrackReviewerPacketPublicSummary } from "@/lib/track-reviewer-packets";

export type CuratedDocument = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  audience: string;
  boundary: string;
  docPath: string;
  rawHref: string;
};

const repositoryBlobBase = "https://github.com/X-PACT/PrivateDAO/blob/main";

const curatedDocuments: CuratedDocument[] = [
  {
    slug: "token-architecture",
    title: "Token Architecture",
    category: "Strategy",
    summary: "Canonical explanation of what the PrivateDAO token does now, what it gates, and how it stays aligned with governance rather than speculative tokenomics.",
    audience: "Judges, buyers, grant reviewers, operators",
    boundary: "Architecture note only; it does not claim a mainnet market token launch or expand token utility beyond the live documented Devnet governance surface.",
    docPath: "docs/token.md",
    rawHref: `${repositoryBlobBase}/docs/token.md`,
  },
  {
    slug: "pdao-token-surface",
    title: "PDAO Token Surface",
    category: "Reviewer core",
    summary: "Reviewer-safe token surface for the live Devnet governance mint, including mint details, attested transactions, disabled mint authority, and product-facing interpretation.",
    audience: "Judges, grant reviewers, buyers, operators",
    boundary: "Live Devnet token truth only; it does not claim a public mainnet token launch or speculative market posture.",
    docPath: "docs/pdao-token.md",
    rawHref: `${repositoryBlobBase}/docs/pdao-token.md`,
  },
  {
    slug: "payments-reviewer-fast-path",
    title: "Payments Reviewer Fast Path",
    category: "Reviewer core",
    summary: "Shortest reviewer-safe path into treasury reviewer packet, canonical custody proof, services payments rail, and command-center payout route.",
    audience: "Judges, grant reviewers, buyers, operators",
    boundary: "Fast-path only; it does not upgrade custody, authority-transfer, or mainnet treasury claims beyond the underlying truth surfaces.",
    docPath: "docs/payments-reviewer-fast-path.md",
    rawHref: `${repositoryBlobBase}/docs/payments-reviewer-fast-path.md`,
  },
  {
    slug: "reviewer-fast-path",
    title: "Reviewer Fast Path",
    category: "Reviewer core",
    summary: "Shortest reviewer path across live proof, V3 hardening, trust links, and launch boundary surfaces.",
    audience: "Judges, auditors, technical reviewers",
    boundary: "Curated in-app view only. The canonical query-driven docs viewer remains in docs/ until full parity exists.",
    docPath: "docs/reviewer-fast-path.md",
    rawHref: `${repositoryBlobBase}/docs/reviewer-fast-path.md`,
  },
  {
    slug: "treasury-reviewer-packet",
    title: "Treasury Reviewer Packet",
    category: "Reviewer core",
    summary: "Generated treasury-facing reviewer packet with strict sender discipline, reference-linked rails, payments fit, reviewer truth links, and exact blocker visibility.",
    audience: "Judges, grant reviewers, buyers, operators",
    boundary: "Reviewer packet only; it does not claim completed custody ceremony or real-funds production readiness.",
    docPath: "docs/treasury-reviewer-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/treasury-reviewer-packet.generated.md`,
  },
  {
    slug: "reviewer-telemetry-packet",
    title: "Reviewer Telemetry Packet",
    category: "Reviewer core",
    summary: "Generated reviewer-safe route into telemetry, hosted reads, runtime evidence, indexed governance, and the infrastructure value layer behind PrivateDAO.",
    audience: "Judges, infrastructure reviewers, grant reviewers, operators",
    boundary: "Generated telemetry packet only; it does not claim external analytics partnerships or production mainnet readiness.",
    docPath: "docs/reviewer-telemetry-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/reviewer-telemetry-packet.generated.md`,
  },
  {
    slug: "read-node-snapshot",
    title: "Read-Node Snapshot",
    category: "Infrastructure",
    summary: "Generated read-node snapshot with indexed proposal counts, runtime path, confidential payout coverage, featured proposal contexts, and current Devnet load profiles.",
    audience: "Judges, infrastructure reviewers, operators, buyers",
    boundary: "Snapshot only; it reflects the indexed Devnet state and does not by itself claim same-domain hosted-read deployment is already live in production.",
    docPath: "docs/read-node/snapshot.generated.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/snapshot.generated.md`,
  },
  {
    slug: "read-node-ops",
    title: "Read-Node Ops Snapshot",
    category: "Infrastructure",
    summary: "Operator-facing read-node overview covering backend coverage, supported Devnet profiles, health endpoints, metrics path, and same-domain deployment target.",
    audience: "Operators, infrastructure reviewers, judges",
    boundary: "Ops packet only; it documents the current backend-indexer posture and deployment target without claiming same-domain reverse proxy closure on the live static site.",
    docPath: "docs/read-node/ops.generated.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/ops.generated.md`,
  },
  {
    slug: "read-node-indexer",
    title: "Read Node And Indexer",
    category: "Infrastructure",
    summary: "Canonical backend read-path brief covering pooled reads, cached runtime inspection, proposal lookup, wallet readiness checks, and the read-only service boundary.",
    audience: "Operators, infrastructure reviewers, judges, buyers",
    boundary: "Architecture and service-boundary packet only; it does not claim same-domain deployment is already live on the current static site.",
    docPath: "docs/read-node/indexer.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/indexer.md`,
  },
  {
    slug: "read-node-same-domain-deploy",
    title: "Read-Node Same-Domain Deploy",
    category: "Infrastructure",
    summary: "Deployment target for serving the static frontend and the read node behind one origin so `/api/v1` becomes a real product rail instead of a documentation-only target.",
    audience: "Operators, infra leads, reviewers",
    boundary: "Deployment target only; the current live site remains static until a separate backend host and reverse proxy are actually cut over.",
    docPath: "docs/read-node/same-domain-deploy.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/same-domain-deploy.md`,
  },
  {
    slug: "read-node-backend-cutover",
    title: "Read-Node Backend Cutover Packet",
    category: "Infrastructure",
    summary: "Generated cutover packet for moving read-node from reviewer-visible evidence into a real hosted backend corridor, with deployment target, public proof, route binding, and UI fallback policy.",
    audience: "Operators, infrastructure reviewers, judges, buyers",
    boundary: "Cutover packet only; it does not claim that same-domain `/api/v1` is already live on the current public static site.",
    docPath: "docs/read-node/backend-cutover-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/read-node/backend-cutover-packet.generated.md`,
  },
  {
    slug: "audit-packet",
    title: "Audit Packet",
    category: "Reviewer core",
    summary: "Generated packet that ties audit-facing evidence, V3 surfaces, and launch materials together.",
    audience: "Judges, auditors, security reviewers",
    boundary: "Rendered in-app as a reviewer-friendly subset. Raw markdown remains the authoritative file.",
    docPath: "docs/audit-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/audit-packet.generated.md`,
  },
  {
    slug: "live-proof-v3",
    title: "Live Proof V3",
    category: "Reviewer core",
    summary: "Dedicated additive hardening proof for Governance V3 and Settlement V3 on Devnet.",
    audience: "Judges, reviewers, protocol operators",
    boundary: "Devnet proof only; not a mainnet custody claim.",
    docPath: "docs/test-wallet-live-proof-v3.generated.md",
    rawHref: `${repositoryBlobBase}/docs/test-wallet-live-proof-v3.generated.md`,
  },
  {
    slug: "governance-hardening-v3",
    title: "Governance Hardening V3",
    category: "Security",
    summary: "Token-supply quorum snapshots, rebate vault isolation, and additive governance policy hardening.",
    audience: "Security reviewers, operators, protocol readers",
    boundary: "Versioned additive hardening; legacy protocol path remains intact.",
    docPath: "docs/governance-hardening-v3.md",
    rawHref: `${repositoryBlobBase}/docs/governance-hardening-v3.md`,
  },
  {
    slug: "zk-capability-matrix",
    title: "ZK Capability Matrix",
    category: "Security",
    summary: "PrivateDAO-specific matrix for what the ZK layer proves today, how it is verified, and what remains explicitly out of scope.",
    audience: "Judges, security reviewers, operators",
    boundary: "Truth-aligned matrix only; it does not upgrade the repo beyond the actual verifier and launch boundaries.",
    docPath: "docs/zk-capability-matrix.md",
    rawHref: `${repositoryBlobBase}/docs/zk-capability-matrix.md`,
  },
  {
    slug: "cryptographic-confidence-engine",
    title: "Cryptographic Confidence Engine",
    category: "Security",
    summary: "Deterministic scoring model for how ZK, REFHE, MagicBlock, Fast RPC, and hardening surfaces change the confidence profile of each proposal pattern.",
    audience: "Judges, security reviewers, operators, buyers",
    boundary: "Interpretation layer only; it does not replace audit, custody, or formal security proofs.",
    docPath: "docs/cryptographic-confidence-engine.md",
    rawHref: `${repositoryBlobBase}/docs/cryptographic-confidence-engine.md`,
  },
  {
    slug: "settlement-hardening-v3",
    title: "Settlement Hardening V3",
    category: "Security",
    summary: "Proposal-scoped settlement policy snapshots, evidence aging, payout caps, and single-use settlement consumption.",
    audience: "Security reviewers, operators, protocol readers",
    boundary: "Curated surface only; confidential payout semantics still depend on the underlying docs and program path.",
    docPath: "docs/settlement-hardening-v3.md",
    rawHref: `${repositoryBlobBase}/docs/settlement-hardening-v3.md`,
  },
  {
    slug: "launch-trust-packet",
    title: "Launch Trust Packet",
    category: "Trust",
    summary: "Custody, audit, pilot, and runtime boundaries tied into one buyer- and reviewer-readable packet.",
    audience: "Buyers, judges, operators",
    boundary: "Keeps pending-external launch work explicit rather than implying mainnet readiness.",
    docPath: "docs/launch-trust-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/launch-trust-packet.generated.md`,
  },
  {
    slug: "mainnet-blockers",
    title: "Mainnet Blockers",
    category: "Trust",
    summary: "Canonical list of pending-external custody, audit, runtime, and release blockers before real-funds cutover.",
    audience: "Operators, buyers, reviewers",
    boundary: "This is a blocker surface, not a launch approval.",
    docPath: "docs/mainnet-blockers.md",
    rawHref: `${repositoryBlobBase}/docs/mainnet-blockers.md`,
  },
  {
    slug: "mainnet-external-closure-packet",
    title: "Mainnet External Closure Packet",
    category: "Trust",
    summary: "Single operator packet for the remaining external-only path: PDAO metadata cutover, custody and authority closure, deploy-only SOL funding, and the exact point at which mainnet can truthfully be called funding-ready.",
    audience: "Operators, buyers, reviewers, release owners",
    boundary: "Closure packet only; it does not claim that external signers, update authority, or cutover ceremony have already executed.",
    docPath: "docs/mainnet-external-closure-packet.md",
    rawHref: `${repositoryBlobBase}/docs/mainnet-external-closure-packet.md`,
  },
  {
    slug: "devnet-rehearsal-multisig",
    title: "Devnet Rehearsal Multisig",
    category: "Trust",
    summary: "Live Devnet rehearsal multisig packet recording the created 2-of-3 signer set, multisig address, and creation signature without overstating it as the production custody closure.",
    audience: "Operators, reviewers, judges",
    boundary: "Rehearsal artifact only; it does not replace the production multisig, mainnet authority transfer, or release ceremony closure.",
    docPath: "docs/devnet-rehearsal-multisig.md",
    rawHref: `${repositoryBlobBase}/docs/devnet-rehearsal-multisig.md`,
  },
  {
    slug: "production-style-custody-closure-plan",
    title: "Production-Style Custody Closure Plan",
    category: "Trust",
    summary: "Minimal-delta plan for moving from the live Devnet rehearsal multisig to a production-shaped custody closure model without overstating that rehearsal artifacts are already production custody.",
    audience: "Operators, reviewers, release owners",
    boundary: "Planning packet only; it does not claim the production multisig, timelock, or authority transfers already exist.",
    docPath: "docs/production-style-custody-closure-plan.md",
    rawHref: `${repositoryBlobBase}/docs/production-style-custody-closure-plan.md`,
  },
  {
    slug: "trust-package",
    title: "Trust Package",
    category: "Trust",
    summary: "Buyer-readable trust and proof narrative that connects product surfaces to security and launch truth.",
    audience: "Buyers, operators, reviewers",
    boundary: "Commercial trust framing remains tied to the underlying proof and blocker docs.",
    docPath: "docs/trust-package.md",
    rawHref: `${repositoryBlobBase}/docs/trust-package.md`,
  },
  {
    slug: "pilot-program",
    title: "Pilot Program",
    category: "Commercial",
    summary: "Week-by-week pilot structure that frames onboarding, trust packets, and execution readiness for early adopters.",
    audience: "Buyers, operators, pilot teams",
    boundary: "Commercial rollout framing only; it does not turn pending-external launch work into shipped infrastructure.",
    docPath: "docs/pilot-program.md",
    rawHref: `${repositoryBlobBase}/docs/pilot-program.md`,
  },
  {
    slug: "service-level-agreement",
    title: "Service Level Agreement",
    category: "Commercial",
    summary: "Hosted ops and service-boundary framing for response expectations, support surfaces, and operator responsibilities.",
    audience: "Buyers, operators, procurement",
    boundary: "Service framing depends on the underlying proof and runtime surfaces; it is not a live enterprise SLA claim by itself.",
    docPath: "docs/service-level-agreement.md",
    rawHref: `${repositoryBlobBase}/docs/service-level-agreement.md`,
  },
  {
    slug: "pricing-model",
    title: "Pricing Model",
    category: "Commercial",
    summary: "Packaging for pilot, API, confidential governance support, and longer-term operating engagements.",
    audience: "Buyers, operators, procurement",
    boundary: "Commercial packaging remains informational until paired with an actual engagement.",
    docPath: "docs/pricing-model.md",
    rawHref: `${repositoryBlobBase}/docs/pricing-model.md`,
  },
  {
    slug: "service-catalog",
    title: "Service Catalog",
    category: "Commercial",
    summary: "Buyer-facing inventory of hosted read API, ops assistance, and confidential governance support services.",
    audience: "Buyers, operators, partnerships",
    boundary: "Service catalog is a product surface, not a claim that every package is currently live-operated.",
    docPath: "docs/service-catalog.md",
    rawHref: `${repositoryBlobBase}/docs/service-catalog.md`,
  },
  {
    slug: "production-custody-ceremony",
    title: "Production Custody Ceremony",
    category: "Operations",
    summary: "Operational handoff for multisig creation, authority transfer, and custody evidence collection before real-funds launch.",
    audience: "Operators, auditors, launch leads",
    boundary: "This is an execution runbook and evidence checklist, not proof that the custody ceremony is already complete.",
    docPath: "docs/production-custody-ceremony.md",
    rawHref: `${repositoryBlobBase}/docs/production-custody-ceremony.md`,
  },
  {
    slug: "canonical-custody-proof",
    title: "Canonical Custody Proof",
    category: "Operations",
    summary: "Repo-backed custody truth packet with exact pending items, observed chain readouts, and explorer-linked closure points.",
    audience: "Operators, auditors, judges, buyers",
    boundary: "Truth packet only; it does not claim that production multisig or authority transfer signatures already exist.",
    docPath: "docs/canonical-custody-proof.generated.md",
    rawHref: `${repositoryBlobBase}/docs/canonical-custody-proof.generated.md`,
  },
  {
    slug: "custody-proof-reviewer-packet",
    title: "Custody Proof Reviewer Packet",
    category: "Reviewer core",
    summary: "Reviewer-facing custody truth packet that condenses what is externally proven now, what is still pending, and the exact strict ingestion route for ceremony evidence.",
    audience: "Judges, auditors, technical reviewers, launch leads",
    boundary: "Reviewer condensation only; it does not claim ceremony completion until the exact external artifacts exist.",
    docPath: "docs/custody-proof-reviewer-packet.generated.md",
    rawHref: `${repositoryBlobBase}/docs/custody-proof-reviewer-packet.generated.md`,
  },
  {
    slug: "track-judge-first-openings",
    title: "Track Judge-First Openings",
    category: "Reviewer core",
    summary: "Canonical 30 to 45 second opening copy for the three priority tracks, kept aligned with the judge-first top strip and reviewer packet.",
    audience: "Judges, reviewers, founders, video editors",
    boundary: "Presentation alignment surface only; it does not change what is proven, pending, or externally blocked.",
    docPath: "docs/track-judge-first-openings.generated.md",
    rawHref: `${repositoryBlobBase}/docs/track-judge-first-openings.generated.md`,
  },
  {
    slug: "strategic-opportunity-readiness-2026",
    title: "Strategic Opportunity Readiness 2026",
    category: "Strategy",
    summary: "Truth-aligned readiness map for accelerator, grant, analytics, confidential-payout, and hardening corridors around the Frontier cycle.",
    audience: "Founders, judges, grant reviewers, operators",
    boundary: "Strategic alignment surface only; it does not claim wins, funding, or integrations that are not already evidenced.",
    docPath: "docs/strategic-opportunity-readiness-2026.md",
    rawHref: `${repositoryBlobBase}/docs/strategic-opportunity-readiness-2026.md`,
  },
  {
    slug: "ecosystem-focus-alignment",
    title: "Ecosystem Focus Alignment",
    category: "Strategy",
    summary: "Generated reviewer-safe mapping from the live product into decentralisation, censorship resistance, DAO tooling, education, developer tooling, payments, and selective cause-driven fit.",
    audience: "Grant reviewers, partners, judges, founders",
    boundary: "Alignment packet only; it does not claim every ecosystem corridor is equally mature or externally validated.",
    docPath: "docs/ecosystem-focus-alignment.generated.md",
    rawHref: `${repositoryBlobBase}/docs/ecosystem-focus-alignment.generated.md`,
  },
  {
    slug: "track-reviewer-packet-colosseum-frontier",
    title: getTrackReviewerPacketPublicLabel("colosseum-frontier"),
    category: "Reviewer core",
    summary: getTrackReviewerPacketPublicSummary("colosseum-frontier"),
    audience: "Judges, reviewers, founders",
    boundary: "Track packet only; it does not alter the underlying trust or blocker truth.",
    docPath: "docs/track-reviewer-packets/colosseum-frontier.generated.md",
    rawHref: `${repositoryBlobBase}/docs/track-reviewer-packets/colosseum-frontier.generated.md`,
  },
  {
    slug: "track-reviewer-packet-privacy-track",
    title: getTrackReviewerPacketPublicLabel("privacy-track"),
    category: "Reviewer core",
    summary: getTrackReviewerPacketPublicSummary("privacy-track"),
    audience: "Judges, reviewers, founders",
    boundary: "Track packet only; it does not alter the underlying trust or blocker truth.",
    docPath: "docs/track-reviewer-packets/privacy-track.generated.md",
    rawHref: `${repositoryBlobBase}/docs/track-reviewer-packets/privacy-track.generated.md`,
  },
  {
    slug: "track-reviewer-packet-rpc-infrastructure",
    title: getTrackReviewerPacketPublicLabel("rpc-infrastructure"),
    category: "Reviewer core",
    summary: getTrackReviewerPacketPublicSummary("rpc-infrastructure"),
    audience: "Judges, reviewers, founders",
    boundary: "Track packet only; it does not alter the underlying trust or blocker truth.",
    docPath: "docs/track-reviewer-packets/rpc-infrastructure.generated.md",
    rawHref: `${repositoryBlobBase}/docs/track-reviewer-packets/rpc-infrastructure.generated.md`,
  },
  {
    slug: "external-audit-engagement",
    title: "External Audit Engagement",
    category: "Operations",
    summary: "Audit intake and boundary packet for external reviewers, including blocker truth and required evidence surfaces.",
    audience: "Auditors, operators, security reviewers",
    boundary: "Captures audit readiness and requested evidence, not external sign-off itself.",
    docPath: "docs/external-audit-engagement.md",
    rawHref: `${repositoryBlobBase}/docs/external-audit-engagement.md`,
  },
  {
    slug: "authority-hardening-mainnet",
    title: "Authority Hardening for Mainnet",
    category: "Operations",
    summary: "Canonical authority-separation brief covering multisig posture, upgrade authority, treasury authority, and admin-boundary discipline before Mainnet.",
    audience: "Operators, auditors, reviewers, buyers",
    boundary: "Launch-discipline surface only; it does not claim the ceremony is already complete.",
    docPath: "docs/authority-hardening-mainnet.md",
    rawHref: `${repositoryBlobBase}/docs/authority-hardening-mainnet.md`,
  },
  {
    slug: "incident-readiness-runbook",
    title: "Incident Readiness Runbook",
    category: "Operations",
    summary: "Canonical runbook for RPC, wallet, instruction, and proposal-state monitoring with a compact operator response loop.",
    audience: "Operators, reviewers, buyers, security readers",
    boundary: "Runbook surface only; it does not claim 24/7 coverage or external IR membership.",
    docPath: "docs/incident-readiness-runbook.md",
    rawHref: `${repositoryBlobBase}/docs/incident-readiness-runbook.md`,
  },
  {
    slug: "monitoring-alert-rules",
    title: "Monitoring Alert Rules",
    category: "Operations",
    summary: "Machine-checked monitoring and alert rules for RPC, wallet, proposal-state, and hosted-read runtime visibility.",
    audience: "Operators, reviewers, buyers, security readers",
    boundary: "Rules surface only; it does not claim external monitoring closure beyond the underlying evidence boundary.",
    docPath: "docs/monitoring-alert-rules.md",
    rawHref: `${repositoryBlobBase}/docs/monitoring-alert-rules.md`,
  },
  {
    slug: "real-device-runtime",
    title: "Real-Device Runtime Evidence",
    category: "Operations",
    summary: "Canonical real-device wallet runtime evidence package with capture coverage, pending targets, and reviewer-safe Devnet proof.",
    audience: "Operators, reviewers, buyers, security readers",
    boundary: "Runtime evidence surface only; it does not claim all target devices are closed beyond the recorded capture set.",
    docPath: "docs/runtime/real-device.generated.md",
    rawHref: `${repositoryBlobBase}/docs/runtime/real-device.generated.md`,
  },
  {
    slug: "frontier-integrations",
    title: "Frontier Integrations",
    category: "Reviewer core",
    summary: "Unified packet for ZK anchors, REFHE envelopes, MagicBlock corridor evidence, and Fast RPC-backed runtime surfaces.",
    audience: "Judges, reviewers, technical operators",
    boundary: "Reviewer-facing integration surface only; source-verifiable external receipts remain a separate launch boundary.",
    docPath: "docs/frontier-integrations.generated.md",
    rawHref: `${repositoryBlobBase}/docs/frontier-integrations.generated.md`,
  },
  {
    slug: "frontier-competition-readiness-2026",
    title: "Frontier Competition Readiness 2026",
    category: "Strategy",
    summary: "Truth-aligned readiness map across the active Superteam and Frontier-adjacent tracks beyond the core Colosseum submission.",
    audience: "Founders, judges, strategy reviewers, operators",
    boundary: "Strategy surface only; it does not claim partner integrations or shipped behaviors beyond what already exists in the repo.",
    docPath: "docs/frontier-competition-readiness-2026.md",
    rawHref: `${repositoryBlobBase}/docs/frontier-competition-readiness-2026.md`,
  },
  {
    slug: "competition-execution-playbook",
    title: "Competition Execution Playbook",
    category: "Strategy",
    summary: "Development playbook for keeping product, demo, docs, proof, and UX aligned with the active competition targets.",
    audience: "Founders, operators, product leads, reviewers",
    boundary: "Execution guidance only; it does not by itself upgrade the repo beyond what is actually implemented.",
    docPath: "docs/competition-execution-playbook.md",
    rawHref: `${repositoryBlobBase}/docs/competition-execution-playbook.md`,
  },
  {
    slug: "colosseum-frontier-2026-operating-brief",
    title: "Colosseum Frontier 2026 Operating Brief",
    category: "Strategy",
    summary: "Operating interpretation of the current Colosseum Frontier, Drift, STRIDE, Anchor v1, and ecosystem signals for PrivateDAO.",
    audience: "Founders, operators, judges, security reviewers",
    boundary: "Operating brief only; it does not replace the underlying proof, launch, or runtime evidence surfaces.",
    docPath: "docs/colosseum-frontier-2026-operating-brief.md",
    rawHref: `${repositoryBlobBase}/docs/colosseum-frontier-2026-operating-brief.md`,
  },
  {
    slug: "frontier-overview-video",
    title: "Frontier Overview Video Package",
    category: "Strategy",
    summary: "Canonical brief for the comprehensive product reel that explains everything PrivateDAO offers and why it is positioned to win across the active track set.",
    audience: "Judges, buyers, operators, content reviewers",
    boundary: "Video brief and asset package only; it does not change the underlying proof or launch boundary documents.",
    docPath: "docs/investor-video.md",
    rawHref: `${repositoryBlobBase}/docs/investor-video.md`,
  },
];

export function getCuratedDocuments() {
  return curatedDocuments;
}

export function getCuratedDocumentsBySlugs(slugs: string[]) {
  const documentMap = new Map(curatedDocuments.map((entry) => [entry.slug, entry]));
  return slugs
    .map((slug) => documentMap.get(slug))
    .filter((entry): entry is CuratedDocument => entry !== undefined);
}

export function getCuratedDocument(slug: string) {
  return curatedDocuments.find((entry) => entry.slug === slug) ?? null;
}

export function getCuratedDocumentContent(slug: string) {
  const entry = getCuratedDocument(slug);
  if (!entry) return null;

  const docsRoot = path.join(/* turbopackIgnore: true */ process.cwd(), "..", "..", "docs");
  const relativeDocPath = entry.docPath.replace(/^docs\//, "");
  const absolutePath = path.join(docsRoot, relativeDocPath);
  if (!fs.existsSync(absolutePath)) {
    throw new Error(`Missing curated document source: ${entry.docPath}`);
  }

  return {
    ...entry,
    content: fs.readFileSync(absolutePath, "utf8"),
  };
}
