import type { SupportedLocale } from "@/lib/i18n";

type EntryFlowCopy = {
  publicDaos: string;
  publicDaoHelper: string;
  loadingDaos: string;
  publicDaoCount: string;
  privateRooms: string;
  privateRoomHelper: string;
  bearerInvite: string;
  bearerInviteHelper: string;
  noInfluence: string;
  noInfluenceHelper: string;
  createRoom: string;
  createRoomHelper: string;
  enterRoom: string;
  enterRoomHelper: string;
  roomName: string;
  invitePlaceholder: string;
  createInvite: string;
  openRoom: string;
  shareInvite: string;
  copyLink: string;
  copyCode: string;
  openInvitation: string;
  invitedRoomUnlocked: string;
  continuePrivateVote: string;
  discussionLocked: string;
  joinOrCreateDao: string;
  createNewPublicDao: string;
  createDaoOnTestnet: string;
};

export const entryFlowCopy: Record<SupportedLocale, EntryFlowCopy> = {
  en: {
    publicDaos: "Join a public live DAO",
    publicDaoHelper: "Public DAO names come from the Testnet read node. Private room names never appear here.",
    loadingDaos: "Loading live DAOs...",
    publicDaoCount: "public DAOs",
    privateRooms: "Private rooms available in this browser",
    privateRoomHelper: "Only the count is shown. Room names, members, notes, and vote intent remain undiscoverable.",
    bearerInvite: "Bearer invite access",
    bearerInviteHelper: "A code, link, or QR grants access. The room name is encrypted inside the invite.",
    noInfluence: "No influence before reveal",
    noInfluenceHelper: "Members cannot see each other’s intent, partial results, or discussion that could shape the vote.",
    createRoom: "Create a new private room",
    createRoomHelper: "Connect a wallet, name the room, then share the generated invite.",
    enterRoom: "Enter a private room",
    enterRoomHelper: "Paste the invitation code sent by the room creator. Public visitors cannot browse room names.",
    roomName: "Private room name",
    invitePlaceholder: "Paste private room invite code",
    createInvite: "Create room and generate invite",
    openRoom: "Open invited room",
    shareInvite: "Share invite",
    copyLink: "Copy link",
    copyCode: "Copy code",
    openInvitation: "Open invitation",
    invitedRoomUnlocked: "Invited room unlocked",
    continuePrivateVote: "Continue to private vote",
    discussionLocked: "Discussion remains locked during the active vote and opens after the result is revealed.",
    joinOrCreateDao: "Join a public DAO or create a new DAO",
    createNewPublicDao: "Create a new public DAO",
    createDaoOnTestnet: "Create DAO on Testnet",
  },
  ar: {
    publicDaos: "انضم إلى DAO عامة حية",
    publicDaoHelper: "أسماء الـ DAO العامة تأتي من عقدة قراءة Testnet. أسماء الغرف الخاصة لا تظهر هنا.",
    loadingDaos: "جارٍ تحميل الـ DAOs الحية...",
    publicDaoCount: "DAOs عامة",
    privateRooms: "الغرف الخاصة المتاحة في هذا المتصفح",
    privateRoomHelper: "يظهر العدد فقط. أسماء الغرف والأعضاء والملاحظات ونوايا التصويت غير قابلة للاكتشاف.",
    bearerInvite: "دخول بكود دعوة",
    bearerInviteHelper: "يمنح الكود أو الرابط أو رمز QR حق الدخول. اسم الغرفة مشفر داخل الدعوة.",
    noInfluence: "لا تأثير قبل الكشف",
    noInfluenceHelper: "لا يرى الأعضاء نوايا بعضهم أو النتائج الجزئية أو نقاشًا قد يؤثر في التصويت.",
    createRoom: "أنشئ غرفة خاصة جديدة",
    createRoomHelper: "صل المحفظة، سم الغرفة، ثم شارك الدعوة المولدة.",
    enterRoom: "ادخل غرفة خاصة",
    enterRoomHelper: "الصق كود الدعوة المرسل من منشئ الغرفة. لا يستطيع الزوار تصفح أسماء الغرف.",
    roomName: "اسم الغرفة الخاصة",
    invitePlaceholder: "الصق كود دعوة الغرفة الخاصة",
    createInvite: "أنشئ الغرفة وولّد الدعوة",
    openRoom: "افتح الغرفة المدعو إليها",
    shareInvite: "شارك الدعوة",
    copyLink: "انسخ الرابط",
    copyCode: "انسخ الكود",
    openInvitation: "افتح الدعوة",
    invitedRoomUnlocked: "تم فتح الغرفة المدعو إليها",
    continuePrivateVote: "تابع إلى التصويت الخاص",
    discussionLocked: "يبقى النقاش مغلقًا أثناء التصويت ويفتح بعد كشف النتيجة.",
    joinOrCreateDao: "انضم إلى DAO عامة أو أنشئ DAO جديدة",
    createNewPublicDao: "أنشئ DAO عامة جديدة",
    createDaoOnTestnet: "أنشئ DAO على Testnet",
  },
  ru: {
    publicDaos: "Присоединиться к публичному DAO",
    publicDaoHelper: "Имена публичных DAO поступают из Testnet read node. Имена приватных комнат здесь не отображаются.",
    loadingDaos: "Загрузка активных DAO...",
    publicDaoCount: "публичных DAO",
    privateRooms: "Приватные комнаты в этом браузере",
    privateRoomHelper: "Показывается только количество. Имена, участники, заметки и намерения голосования скрыты.",
    bearerInvite: "Доступ по приглашению",
    bearerInviteHelper: "Код, ссылка или QR дают доступ. Название комнаты зашифровано внутри приглашения.",
    noInfluence: "Без влияния до раскрытия",
    noInfluenceHelper: "Участники не видят намерения друг друга, частичные результаты или обсуждение, способное повлиять на голосование.",
    createRoom: "Создать приватную комнату",
    createRoomHelper: "Подключите кошелек, назовите комнату и поделитесь приглашением.",
    enterRoom: "Войти в приватную комнату",
    enterRoomHelper: "Вставьте код приглашения от создателя комнаты. Публичные посетители не могут просматривать названия.",
    roomName: "Название приватной комнаты",
    invitePlaceholder: "Вставьте код приглашения",
    createInvite: "Создать комнату и приглашение",
    openRoom: "Открыть комнату",
    shareInvite: "Поделиться приглашением",
    copyLink: "Копировать ссылку",
    copyCode: "Копировать код",
    openInvitation: "Открыть приглашение",
    invitedRoomUnlocked: "Комната открыта",
    continuePrivateVote: "Перейти к приватному голосованию",
    discussionLocked: "Обсуждение закрыто во время голосования и открывается после раскрытия результата.",
    joinOrCreateDao: "Присоединиться к публичному DAO или создать новое",
    createNewPublicDao: "Создать новое публичное DAO",
    createDaoOnTestnet: "Создать DAO в Testnet",
  },
  uk: {
    publicDaos: "Приєднатися до публічного DAO",
    publicDaoHelper: "Назви публічних DAO надходять із Testnet read node. Назви приватних кімнат тут не показуються.",
    loadingDaos: "Завантаження активних DAO...",
    publicDaoCount: "публічних DAO",
    privateRooms: "Приватні кімнати в цьому браузері",
    privateRoomHelper: "Показується лише кількість. Назви, учасники, нотатки та наміри голосування приховані.",
    bearerInvite: "Доступ за запрошенням",
    bearerInviteHelper: "Код, посилання або QR надають доступ. Назва кімнати зашифрована у запрошенні.",
    noInfluence: "Без впливу до розкриття",
    noInfluenceHelper: "Учасники не бачать намірів одне одного, часткових результатів або обговорення, що може вплинути на голосування.",
    createRoom: "Створити приватну кімнату",
    createRoomHelper: "Підключіть гаманець, назвіть кімнату та поділіться запрошенням.",
    enterRoom: "Увійти до приватної кімнати",
    enterRoomHelper: "Вставте код запрошення від творця кімнати. Публічні відвідувачі не можуть переглядати назви.",
    roomName: "Назва приватної кімнати",
    invitePlaceholder: "Вставте код запрошення",
    createInvite: "Створити кімнату і запрошення",
    openRoom: "Відкрити кімнату",
    shareInvite: "Поділитися запрошенням",
    copyLink: "Копіювати посилання",
    copyCode: "Копіювати код",
    openInvitation: "Відкрити запрошення",
    invitedRoomUnlocked: "Кімнату відкрито",
    continuePrivateVote: "Перейти до приватного голосування",
    discussionLocked: "Обговорення закрите під час голосування і відкривається після розкриття результату.",
    joinOrCreateDao: "Приєднатися до публічного DAO або створити нове",
    createNewPublicDao: "Створити нове публічне DAO",
    createDaoOnTestnet: "Створити DAO у Testnet",
  },
  pl: {
    publicDaos: "Dołącz do publicznego DAO",
    publicDaoHelper: "Nazwy publicznych DAO pochodzą z węzła odczytu Testnet. Nazwy prywatnych pokoi nie są tu widoczne.",
    loadingDaos: "Ładowanie aktywnych DAO...",
    publicDaoCount: "publicznych DAO",
    privateRooms: "Prywatne pokoje w tej przeglądarce",
    privateRoomHelper: "Widoczna jest tylko liczba. Nazwy, członkowie, notatki i zamiary głosowania pozostają ukryte.",
    bearerInvite: "Dostęp przez zaproszenie",
    bearerInviteHelper: "Kod, link lub QR daje dostęp. Nazwa pokoju jest zaszyfrowana w zaproszeniu.",
    noInfluence: "Bez wpływu przed ujawnieniem",
    noInfluenceHelper: "Członkowie nie widzą zamiarów innych, częściowych wyników ani dyskusji, która mogłaby wpłynąć na głos.",
    createRoom: "Utwórz prywatny pokój",
    createRoomHelper: "Połącz portfel, nazwij pokój i udostępnij wygenerowane zaproszenie.",
    enterRoom: "Wejdź do prywatnego pokoju",
    enterRoomHelper: "Wklej kod zaproszenia od twórcy pokoju. Publiczni odwiedzający nie mogą przeglądać nazw.",
    roomName: "Nazwa prywatnego pokoju",
    invitePlaceholder: "Wklej kod zaproszenia",
    createInvite: "Utwórz pokój i zaproszenie",
    openRoom: "Otwórz zaproszony pokój",
    shareInvite: "Udostępnij zaproszenie",
    copyLink: "Kopiuj link",
    copyCode: "Kopiuj kod",
    openInvitation: "Otwórz zaproszenie",
    invitedRoomUnlocked: "Pokój odblokowany",
    continuePrivateVote: "Przejdź do prywatnego głosowania",
    discussionLocked: "Dyskusja pozostaje zamknięta podczas głosowania i otwiera się po ujawnieniu wyniku.",
    joinOrCreateDao: "Dołącz do publicznego DAO lub utwórz nowe",
    createNewPublicDao: "Utwórz nowe publiczne DAO",
    createDaoOnTestnet: "Utwórz DAO w Testnet",
  },
  hi: {
    publicDaos: "सार्वजनिक लाइव DAO में शामिल हों",
    publicDaoHelper: "सार्वजनिक DAO नाम Testnet read node से आते हैं। निजी कमरे के नाम यहाँ कभी नहीं दिखते।",
    loadingDaos: "लाइव DAO लोड हो रहे हैं...",
    publicDaoCount: "सार्वजनिक DAO",
    privateRooms: "इस ब्राउज़र में उपलब्ध निजी कमरे",
    privateRoomHelper: "केवल संख्या दिखाई जाती है। नाम, सदस्य, नोट्स और वोट की मंशा छिपी रहती है।",
    bearerInvite: "निमंत्रण से प्रवेश",
    bearerInviteHelper: "कोड, लिंक या QR से प्रवेश मिलता है। कमरे का नाम निमंत्रण में एन्क्रिप्टेड रहता है।",
    noInfluence: "रिवील से पहले कोई प्रभाव नहीं",
    noInfluenceHelper: "सदस्य एक-दूसरे की मंशा, आंशिक परिणाम या वोट को प्रभावित करने वाली चर्चा नहीं देख सकते।",
    createRoom: "नया निजी कमरा बनाएँ",
    createRoomHelper: "वॉलेट कनेक्ट करें, कमरे का नाम दें और तैयार निमंत्रण साझा करें।",
    enterRoom: "निजी कमरे में प्रवेश करें",
    enterRoomHelper: "कमरे के निर्माता से मिला निमंत्रण कोड पेस्ट करें। सार्वजनिक विज़िटर कमरे के नाम नहीं देख सकते।",
    roomName: "निजी कमरे का नाम",
    invitePlaceholder: "निजी कमरे का निमंत्रण कोड पेस्ट करें",
    createInvite: "कमरा बनाएँ और निमंत्रण तैयार करें",
    openRoom: "आमंत्रित कमरा खोलें",
    shareInvite: "निमंत्रण साझा करें",
    copyLink: "लिंक कॉपी करें",
    copyCode: "कोड कॉपी करें",
    openInvitation: "निमंत्रण खोलें",
    invitedRoomUnlocked: "आमंत्रित कमरा खुल गया",
    continuePrivateVote: "निजी वोट पर जाएँ",
    discussionLocked: "सक्रिय वोट के दौरान चर्चा बंद रहती है और परिणाम रिवील होने के बाद खुलती है।",
    joinOrCreateDao: "सार्वजनिक DAO में शामिल हों या नया बनाएँ",
    createNewPublicDao: "नया सार्वजनिक DAO बनाएँ",
    createDaoOnTestnet: "Testnet पर DAO बनाएँ",
  },
  ko: {
    publicDaos: "공개 라이브 DAO 참여",
    publicDaoHelper: "공개 DAO 이름은 Testnet 읽기 노드에서 가져옵니다. 비공개 방 이름은 표시되지 않습니다.",
    loadingDaos: "라이브 DAO 불러오는 중...",
    publicDaoCount: "공개 DAO",
    privateRooms: "이 브라우저에서 사용할 수 있는 비공개 방",
    privateRoomHelper: "개수만 표시됩니다. 방 이름, 멤버, 메모, 투표 의도는 검색할 수 없습니다.",
    bearerInvite: "초대 코드 접근",
    bearerInviteHelper: "코드, 링크 또는 QR로 접근합니다. 방 이름은 초대 안에 암호화됩니다.",
    noInfluence: "공개 전 영향 신호 없음",
    noInfluenceHelper: "멤버는 서로의 의도, 부분 결과 또는 투표에 영향을 줄 토론을 볼 수 없습니다.",
    createRoom: "새 비공개 방 만들기",
    createRoomHelper: "지갑을 연결하고 방 이름을 정한 뒤 생성된 초대를 공유하세요.",
    enterRoom: "비공개 방 입장",
    enterRoomHelper: "방 생성자가 보낸 초대 코드를 붙여 넣으세요. 공개 방문자는 방 이름을 탐색할 수 없습니다.",
    roomName: "비공개 방 이름",
    invitePlaceholder: "비공개 방 초대 코드 붙여넣기",
    createInvite: "방 만들기 및 초대 생성",
    openRoom: "초대된 방 열기",
    shareInvite: "초대 공유",
    copyLink: "링크 복사",
    copyCode: "코드 복사",
    openInvitation: "초대 열기",
    invitedRoomUnlocked: "초대된 방 열림",
    continuePrivateVote: "비공개 투표로 계속",
    discussionLocked: "활성 투표 중에는 토론이 잠기며 결과 공개 후 열립니다.",
    joinOrCreateDao: "공개 DAO에 참여하거나 새 DAO 만들기",
    createNewPublicDao: "새 공개 DAO 만들기",
    createDaoOnTestnet: "Testnet에서 DAO 만들기",
  },
  es: {
    publicDaos: "Unirse a un DAO público activo",
    publicDaoHelper: "Los nombres de DAO públicos vienen del nodo de lectura Testnet. Los nombres de salas privadas nunca aparecen aquí.",
    loadingDaos: "Cargando DAOs activos...",
    publicDaoCount: "DAOs públicos",
    privateRooms: "Salas privadas disponibles en este navegador",
    privateRoomHelper: "Solo se muestra la cantidad. Los nombres, miembros, notas e intención de voto no son detectables.",
    bearerInvite: "Acceso mediante invitación",
    bearerInviteHelper: "Un código, enlace o QR concede acceso. El nombre de la sala está cifrado dentro de la invitación.",
    noInfluence: "Sin influencia antes del reveal",
    noInfluenceHelper: "Los miembros no pueden ver la intención de otros, resultados parciales ni discusiones que influyan en el voto.",
    createRoom: "Crear una sala privada",
    createRoomHelper: "Conecta una billetera, nombra la sala y comparte la invitación generada.",
    enterRoom: "Entrar a una sala privada",
    enterRoomHelper: "Pega el código enviado por el creador. Los visitantes públicos no pueden explorar nombres de salas.",
    roomName: "Nombre de la sala privada",
    invitePlaceholder: "Pega el código de invitación",
    createInvite: "Crear sala y generar invitación",
    openRoom: "Abrir sala invitada",
    shareInvite: "Compartir invitación",
    copyLink: "Copiar enlace",
    copyCode: "Copiar código",
    openInvitation: "Abrir invitación",
    invitedRoomUnlocked: "Sala invitada desbloqueada",
    continuePrivateVote: "Continuar al voto privado",
    discussionLocked: "La discusión permanece bloqueada durante la votación y se abre después de revelar el resultado.",
    joinOrCreateDao: "Unirse a un DAO público o crear uno nuevo",
    createNewPublicDao: "Crear un nuevo DAO público",
    createDaoOnTestnet: "Crear DAO en Testnet",
  },
  it: {
    publicDaos: "Partecipa a un DAO pubblico attivo",
    publicDaoHelper: "I nomi dei DAO pubblici arrivano dal read node Testnet. I nomi delle stanze private non appaiono mai qui.",
    loadingDaos: "Caricamento DAO attivi...",
    publicDaoCount: "DAO pubblici",
    privateRooms: "Stanze private disponibili in questo browser",
    privateRoomHelper: "Viene mostrato solo il numero. Nomi, membri, note e intenzioni di voto restano non rilevabili.",
    bearerInvite: "Accesso tramite invito",
    bearerInviteHelper: "Un codice, link o QR concede l'accesso. Il nome della stanza è cifrato nell'invito.",
    noInfluence: "Nessuna influenza prima del reveal",
    noInfluenceHelper: "I membri non vedono le intenzioni altrui, risultati parziali o discussioni che possano influenzare il voto.",
    createRoom: "Crea una nuova stanza privata",
    createRoomHelper: "Connetti un wallet, assegna un nome alla stanza e condividi l'invito generato.",
    enterRoom: "Entra in una stanza privata",
    enterRoomHelper: "Incolla il codice inviato dal creatore. I visitatori pubblici non possono sfogliare i nomi delle stanze.",
    roomName: "Nome della stanza privata",
    invitePlaceholder: "Incolla il codice di invito",
    createInvite: "Crea stanza e genera invito",
    openRoom: "Apri stanza invitata",
    shareInvite: "Condividi invito",
    copyLink: "Copia link",
    copyCode: "Copia codice",
    openInvitation: "Apri invito",
    invitedRoomUnlocked: "Stanza invitata sbloccata",
    continuePrivateVote: "Continua al voto privato",
    discussionLocked: "La discussione resta bloccata durante il voto e si apre dopo il reveal del risultato.",
    joinOrCreateDao: "Partecipa a un DAO pubblico o creane uno nuovo",
    createNewPublicDao: "Crea un nuovo DAO pubblico",
    createDaoOnTestnet: "Crea DAO su Testnet",
  },
};
