// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 X-PACT. AGPL-3.0-or-later.
// Generated by scripts/build-onchain-ui-parity.ts. Do not edit manually.

export const PRIVATE_DAO_PROGRAM_ID = "5AhUsbQ4mJ8Xh7QJEomuS85qGgmK9iNvFqzF669Y7Psx" as const;
export const PRIVATE_DAO_GOVERNANCE_MINT = "AZUkprJDfJPgAp7L4z3TpCV3KHqLiA8RjHAVhK9HCvDt" as const;
export const PRIVATE_DAO_GOVERNANCE_TOKEN_PROGRAM = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as const;
export const PRIVATE_DAO_CORE_INSTRUCTION_PARITY = {
  "initialize_dao": {
    "instructionName": "initialize_dao",
    "displayName": "Create DAO",
    "summary": "Initializes the DAO PDA with the governance mint, quorum, reveal window, execution delay, and voting mode.",
    "fieldOrder": [
      "dao_name",
      "quorum_percentage",
      "governance_token_required",
      "reveal_window_seconds",
      "execution_delay_seconds",
      "voting_config"
    ],
    "args": [
      {
        "name": "dao_name",
        "type": "string"
      },
      {
        "name": "quorum_percentage",
        "type": "u8"
      },
      {
        "name": "governance_token_required",
        "type": "u64"
      },
      {
        "name": "reveal_window_seconds",
        "type": "i64"
      },
      {
        "name": "execution_delay_seconds",
        "type": "i64"
      },
      {
        "name": "voting_config",
        "type": "{\"defined\":{\"name\":\"VotingConfig\"}}"
      }
    ],
    "accounts": [
      {
        "name": "dao",
        "writable": true,
        "signer": false
      },
      {
        "name": "governance_token",
        "writable": false,
        "signer": false
      },
      {
        "name": "authority",
        "writable": true,
        "signer": true
      },
      {
        "name": "system_program",
        "writable": false,
        "signer": false
      }
    ],
    "reviewChecklist": [
      "Confirm the DAO name matches the expected signer-owned namespace.",
      "Confirm the governance mint is the intended token surface for this DAO.",
      "Confirm reveal window and execution delay match the operating policy.",
      "Confirm the voting mode is the intended on-chain chamber model."
    ],
    "validationRules": [
      "dao_name length must be 64 bytes or less",
      "quorum_percentage must be between 1 and 100",
      "reveal_window_seconds must be at least the protocol minimum",
      "execution_delay_seconds must be zero or positive",
      "voting_config must pass validate_voting_config"
    ]
  },
  "create_proposal": {
    "instructionName": "create_proposal",
    "displayName": "Create Proposal",
    "summary": "Creates a proposal PDA with proposal text, voting window, reveal window, and an optional treasury action.",
    "fieldOrder": [
      "title",
      "description",
      "voting_duration_seconds",
      "treasury_action"
    ],
    "args": [
      {
        "name": "title",
        "type": "string"
      },
      {
        "name": "description",
        "type": "string"
      },
      {
        "name": "voting_duration_seconds",
        "type": "i64"
      },
      {
        "name": "treasury_action",
        "type": "{\"option\":{\"defined\":{\"name\":\"TreasuryAction\"}}}"
      }
    ],
    "accounts": [
      {
        "name": "dao",
        "writable": true,
        "signer": false
      },
      {
        "name": "proposal",
        "writable": true,
        "signer": false
      },
      {
        "name": "proposer_token_account",
        "writable": false,
        "signer": false
      },
      {
        "name": "proposer",
        "writable": true,
        "signer": true
      },
      {
        "name": "system_program",
        "writable": false,
        "signer": false
      }
    ],
    "reviewChecklist": [
      "Confirm the proposer token account belongs to the signing proposer wallet.",
      "Confirm the proposer token account mint matches dao.governance_token.",
      "Confirm the title, description, and duration are the intended values.",
      "If treasury_action is present, confirm recipient, amount, and token mint are correct."
    ],
    "validationRules": [
      "title length must be 128 bytes or less",
      "description length must be 1024 bytes or less",
      "voting_duration_seconds must meet the protocol minimum",
      "treasury_action must pass validate_treasury_action when present",
      "proposer token balance must be non-zero and satisfy governance_token_required if configured"
    ]
  },
  "commit_vote": {
    "instructionName": "commit_vote",
    "displayName": "Commit Vote",
    "summary": "Stores the vote commitment in the proposal-scoped voter record using the canonical commit-reveal preimage.",
    "fieldOrder": [
      "commitment",
      "voter_reveal_authority"
    ],
    "args": [
      {
        "name": "commitment",
        "type": "{\"array\":[\"u8\",32]}"
      },
      {
        "name": "voter_reveal_authority",
        "type": "{\"option\":\"pubkey\"}"
      }
    ],
    "accounts": [
      {
        "name": "dao",
        "writable": false,
        "signer": false
      },
      {
        "name": "proposal",
        "writable": true,
        "signer": false
      },
      {
        "name": "voter_record",
        "writable": true,
        "signer": false
      },
      {
        "name": "delegation_marker",
        "writable": false,
        "signer": false
      },
      {
        "name": "voter_token_account",
        "writable": false,
        "signer": false
      },
      {
        "name": "voter",
        "writable": true,
        "signer": true
      },
      {
        "name": "token_program",
        "writable": false,
        "signer": false
      },
      {
        "name": "system_program",
        "writable": false,
        "signer": false
      }
    ],
    "reviewChecklist": [
      "Confirm the proposal PDA matches the DAO and proposal id you intend to vote on.",
      "Confirm the commitment was derived from vote byte, salt, proposal pubkey, and voter pubkey in that order.",
      "Confirm the voter token account belongs to the signer and matches the DAO governance mint.",
      "Confirm no delegation marker already exists for the same proposal and voter."
    ],
    "validationRules": [
      "proposal.status must be Voting",
      "current time must be before proposal.voting_end",
      "voter token balance must be non-zero and satisfy governance_token_required if configured",
      "delegation marker must not already exist for this proposal and voter",
      "voter_record.has_committed must be false"
    ]
  },
  "reveal_vote": {
    "instructionName": "reveal_vote",
    "displayName": "Reveal Vote",
    "summary": "Recomputes the canonical vote commitment and updates tallies only when the voter or authorized keeper reveals within the reveal window.",
    "fieldOrder": [
      "vote",
      "salt"
    ],
    "args": [
      {
        "name": "vote",
        "type": "bool"
      },
      {
        "name": "salt",
        "type": "{\"array\":[\"u8\",32]}"
      }
    ],
    "accounts": [
      {
        "name": "proposal",
        "writable": true,
        "signer": false
      },
      {
        "name": "voter_record",
        "writable": true,
        "signer": false
      },
      {
        "name": "revealer",
        "writable": true,
        "signer": true
      }
    ],
    "reviewChecklist": [
      "Confirm the operation is reveal, not commit or execute.",
      "Confirm the proposal id and voter record belong to the same proposal.",
      "Confirm the salt and vote value reproduce the stored commitment exactly.",
      "Confirm the signer is either the original voter or voter_reveal_authority."
    ],
    "validationRules": [
      "proposal.status must still be Voting",
      "current time must be at or after proposal.voting_end",
      "current time must be before proposal.reveal_end",
      "voter_record must have a prior commitment and no prior reveal",
      "recomputed commitment must match the stored commitment"
    ]
  },
  "finalize_proposal": {
    "instructionName": "finalize_proposal",
    "displayName": "Finalize Proposal",
    "summary": "Computes pass/fail after reveal_end and sets execution_unlocks_at for passed proposals.",
    "fieldOrder": [],
    "args": [],
    "accounts": [
      {
        "name": "dao",
        "writable": false,
        "signer": false
      },
      {
        "name": "proposal",
        "writable": true,
        "signer": false
      },
      {
        "name": "finalizer",
        "writable": false,
        "signer": true
      }
    ],
    "reviewChecklist": [
      "Confirm reveal_end has elapsed before finalization is attempted.",
      "Confirm the proposal has not already been finalized.",
      "Confirm the finalizer is using the same DAO and proposal PDAs shown in the UI."
    ],
    "validationRules": [
      "current time must be at or after proposal.reveal_end",
      "proposal.status must still be Voting",
      "finalization uses the DAO voting configuration and chamber weights already stored on-chain"
    ]
  },
  "execute_proposal": {
    "instructionName": "execute_proposal",
    "displayName": "Execute Proposal",
    "summary": "Executes the treasury action only after pass state, timelock expiry, and recipient validation succeed.",
    "fieldOrder": [],
    "args": [],
    "accounts": [
      {
        "name": "dao",
        "writable": false,
        "signer": false
      },
      {
        "name": "proposal",
        "writable": true,
        "signer": false
      },
      {
        "name": "treasury",
        "writable": true,
        "signer": false
      },
      {
        "name": "executor",
        "writable": false,
        "signer": true
      },
      {
        "name": "treasury_recipient",
        "writable": true,
        "signer": false
      },
      {
        "name": "treasury_token_account",
        "writable": true,
        "signer": false
      },
      {
        "name": "recipient_token_account",
        "writable": true,
        "signer": false
      },
      {
        "name": "confidential_payout_plan",
        "writable": false,
        "signer": false
      },
      {
        "name": "token_program",
        "writable": false,
        "signer": false
      },
      {
        "name": "system_program",
        "writable": false,
        "signer": false
      }
    ],
    "reviewChecklist": [
      "Confirm the operation type is execute and not finalize or reveal.",
      "Confirm proposal.status is Passed and execution_unlocks_at has elapsed.",
      "Confirm treasury recipient, amount, mint, and token path match the approved treasury action.",
      "Confirm this is the standard execute path and not a confidential payout execution path."
    ],
    "validationRules": [
      "proposal.status must be Passed",
      "proposal.is_executed must be false",
      "current time must be at or after proposal.execution_unlocks_at",
      "confidential_payout_plan must not exist for the standard execute path",
      "treasury_recipient must match treasury_action.recipient for SendSol and SendToken"
    ]
  }
} as const;

export type CoreGovernanceInstructionName = keyof typeof PRIVATE_DAO_CORE_INSTRUCTION_PARITY;
