// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 X-PACT. AGPL-3.0-or-later.
// Generated by scripts/build-read-node-snapshot.ts. Do not edit manually.

export const READ_NODE_FEATURED_PROPOSAL_CONTEXTS = {
  "payroll": {
    "sourceType": "runtime-indexed",
    "sourceLabel": "Backend-indexed proposal record: Encrypted manifest bound MagicBlock bonus v2 (Executed)",
    "indexedPhase": "Executed",
    "proposalAccount": "52UpWHJodPWQzpR8u2qqpgwo3jRB7mvjgwCnf8oSJuXX",
    "daoAccount": "9yi2TGLcENufbRPVbEJH3BWJWrqsGxLfG6G7qJmUS8r6",
    "executionTarget": "Aggregate payroll payout to the confidential settlement wallet after governance clearance.",
    "recipient": "2TrX1tAJjcPcV8nc6f8LBAe97jZVi5hPG6jND3Wb1mCk",
    "recipientLabel": "Confidential settlement wallet",
    "recipientKnown": true,
    "amount": 1000000,
    "amountDisplay": "1,000,000 raw token units",
    "mintSymbol": "SPL token",
    "mintAddress": "9RqMo8zzCwH3XDCJq6STJSzrVS39MkWz4q7zXsYznsdC",
    "timelockHours": 0.001389,
    "timelockLabel": "5 second on-chain execution delay from the indexed DAO record",
    "historicalUseCount": 1,
    "repeatedAttempts": 0,
    "baselineAmount": 1000000,
    "presentationStatus": "Executed",
    "presentationWindow": "Commit closed · Reveal complete · Executed on devnet",
    "presentationTreasury": "Confidential payout executed for 1,000,000 units to 2TrX…1mCk via mint 9RqM…nsdC",
    "phaseMappingLabel": "Executed indexed phase maps to Executed in the product surface",
    "txContext": {
      "proofStatus": "verified-devnet-confidential-path",
      "evidenceRoute": "/proof/?judge=1",
      "executeSignature": "LoNED2YKkYWxaQbFV4y8fCzqGi5YrpPSruJYppqfvcTyAJ2zU5HM92QEsPNydQb26abE7qp2kB7hCNPJFbVUUPA"
    }
  },
  "gaming": {
    "sourceType": "runtime-indexed",
    "sourceLabel": "Backend-indexed proposal record: Devnet Confidential MagicBlock REFHE V3 (Finalized)",
    "indexedPhase": "Finalized",
    "proposalAccount": "QwRmN5WFDL7AxXT8fjcZNhy53cgLk7UWnJ5qB2CmRaJ",
    "daoAccount": "2UBuKLVfY3kJ22WAmYEZDh71bWhJp2euRpPDq2qT1S8p",
    "executionTarget": "MagicBlock reward corridor with settlement gating before final distribution.",
    "recipient": "2TrX1tAJjcPcV8nc6f8LBAe97jZVi5hPG6jND3Wb1mCk",
    "recipientLabel": "MagicBlock settlement corridor",
    "recipientKnown": true,
    "amount": 1000000,
    "amountDisplay": "1,000,000 raw token units",
    "mintSymbol": "SPL token",
    "mintAddress": "58WbHdCZgFhiAnVNjQqs4LeZReeYW6YdEZQin4civfMh",
    "timelockHours": 0.001389,
    "timelockLabel": "5 second on-chain execution delay from the indexed DAO record",
    "historicalUseCount": 1,
    "repeatedAttempts": 1,
    "baselineAmount": 1000000,
    "presentationStatus": "Evidence gated",
    "presentationWindow": "Voting closed · Finalized on devnet · Settlement evidence still incomplete",
    "presentationTreasury": "Confidential payout still gated for 1,000,000 units to 2TrX…1mCk via mint 58Wb…vfMh",
    "phaseMappingLabel": "Finalized indexed phase maps to Evidence gated in the product surface",
    "txContext": {
      "proofStatus": "runtime-indexed-confidential-path",
      "evidenceRoute": "/proof/?judge=1"
    }
  },
  "grant": {
    "sourceType": "runtime-indexed",
    "sourceLabel": "Backend-indexed proposal record: Multi proposal A (Executed)",
    "indexedPhase": "Executed",
    "proposalAccount": "A5Hd89vpCTVPALhuwurLQvyAkHyrNGhvZtAcJvBmuJ9U",
    "daoAccount": "EyLjhct7TJwb7pa1HssjwZcTT9WMq6Vq5aAxTKsK1b8t",
    "executionTarget": "Send treasury funds to the approved beneficiary after governance finalization and unlock.",
    "recipient": "AbF9Q5WkSgQRMV8R7HwHa1WgoPAytM6XxyZVzf7fFWDy",
    "recipientLabel": "Treasury beneficiary",
    "recipientKnown": true,
    "amount": 0.02,
    "amountDisplay": "0.02 SOL",
    "mintSymbol": "SOL",
    "mintAddress": null,
    "timelockHours": 0.001667,
    "timelockLabel": "6 second on-chain execution delay from the indexed DAO record",
    "historicalUseCount": 1,
    "repeatedAttempts": 0,
    "baselineAmount": 0.02,
    "presentationStatus": "Executed",
    "presentationWindow": "Commit closed · Reveal complete · Executed on devnet",
    "presentationTreasury": "0.02 SOL sent to AbF9…FWDy",
    "phaseMappingLabel": "Executed indexed phase maps to Executed in the product surface",
    "txContext": {
      "proofStatus": "verified-devnet-governance-path",
      "evidenceRoute": "/documents/reviewer-fast-path",
      "createProposalSignature": "u7V1B5cUx91KY69pE9JSMfkAt9SFcVZbDrP9Nsv3XqatNHfr1P2jZwKkaCHCZuPyqm4WJgmH8w8SDUQoJQc938S",
      "commitSignature": "67fRsWN8qcndxA8Cb7navZ77BnnLwj4msbNnffcYrwfiv924LKW8vyWu31GRi7AXVfMjGuHytkt8JN5jFKNzCwoR",
      "revealSignature": "43N2Yxf177oUtAh9NxuR5hwJiAhw1DDKkaR8mutzkwYrnrr4xX1DRpJ9QG1y8Y3vmwzM5RxASqRkNybseEWLpazQ",
      "finalizeSignature": "2RcCc2d5e2Q7sSV5EJkCJ2JFEhSCSRRMyvPa2k1ViUwPjcVzuEq1wydKxB3bi4gUpLc6Nj3v9dtqN843juaF51ud",
      "executeSignature": "5FYTXGHufj6Qa2azAE8WEvWZk8wfJX3BRjxpbFaWfc9bpP9weyeNWNGopMFnjtMpWD1rboRPxhd7Q8NwcqMEuVAb"
    }
  }
} as const;

export type ReadNodeFeaturedProposalContextKey = keyof typeof READ_NODE_FEATURED_PROPOSAL_CONTEXTS;
