// Generated by scripts/build-web-runtime-catalog.ts. Do not edit by hand.

export const runtimeCatalog = {
  "generatedFrom": "packages/privatedao-runtime/src/catalog.ts and networks.ts",
  "products": [
    {
      "id": "blind-verification",
      "name": "Blind Verification",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "verification.blind.prove",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.blind.prove",
              "method": null,
              "note": "Kernel adapter delegates to the HTTPS proof service and accepts only an observed successful public proof package."
            }
          ]
        }
      ]
    },
    {
      "id": "record-verification",
      "name": "Record Verification",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "verification.record.create",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.record.create",
              "method": null,
              "note": "Kernel-native digest and selective disclosure artifact; no public URL or on-chain anchor is created."
            }
          ]
        },
        {
          "id": "verification.record.verify",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.record.verify",
              "method": null,
              "note": "Kernel-native digest verification; no source payload is returned and no on-chain anchor is claimed."
            }
          ]
        }
      ]
    },
    {
      "id": "payroll",
      "name": "Confidential Payroll",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "payroll.calculate",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://payroll.calculate",
              "method": null,
              "note": "Kernel-native deterministic calculation; no wallet signature or settlement is performed."
            }
          ]
        },
        {
          "id": "payroll.approve",
          "version": "1.0",
          "requiresSignature": true,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "unbound",
              "entrypoint": null,
              "method": null,
              "note": "Payroll approval state machine is not yet exposed as a Kernel-backed application action."
            }
          ]
        },
        {
          "id": "payroll.settle",
          "version": "1.0",
          "requiresSignature": true,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "legacy-provider",
              "entrypoint": "/api/private-payout/prepare",
              "method": "POST",
              "note": "Existing private-payout provider route; it is not evidence of an end-to-end payroll settlement."
            }
          ]
        }
      ]
    },
    {
      "id": "treasury",
      "name": "Private Treasury",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "treasury.policy.check",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://treasury.policy.check",
              "method": null,
              "note": "Kernel-native deterministic policy evaluation; no wallet signature or treasury movement is performed."
            }
          ]
        }
      ]
    },
    {
      "id": "governance",
      "name": "Private Governance",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "governance.proposal.execute",
          "version": "1.0",
          "requiresSignature": true,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "unbound",
              "entrypoint": null,
              "method": null,
              "note": "No exact Kernel-backed governance execution action is exposed by the web app."
            }
          ]
        }
      ]
    },
    {
      "id": "auction",
      "name": "Private Auctions",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "auction.bid.commit",
          "version": "1.0",
          "requiresSignature": true,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "legacy-provider",
              "entrypoint": "/api/auctions/sealed/run",
              "method": "POST",
              "note": "Existing sealed-auction route; not yet routed through ProductExecutionGateway."
            }
          ]
        },
        {
          "id": "auction.settle",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://auction.settle",
              "method": null,
              "note": "Kernel adapter delegates to the HTTPS outcome-proof service; it proves an already-bound result and does not claim token movement or an on-chain signature."
            }
          ]
        }
      ]
    },
    {
      "id": "agent",
      "name": "Agent Marketplace",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "agent.discover",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://agent.discover",
              "method": null,
              "note": "Kernel-native read-only Agent Card fetch; no agent activity or external adoption is inferred."
            }
          ]
        },
        {
          "id": "agent.invoke",
          "version": "1.0",
          "requiresSignature": true,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "unbound",
              "entrypoint": null,
              "method": null,
              "note": "No Kernel-backed Agent Marketplace invocation action is exposed by the web app."
            }
          ]
        }
      ]
    }
  ],
  "networks": [
    {
      "id": "solana-devnet",
      "label": "Solana Devnet",
      "family": "solana",
      "stage": "available",
      "environment": "devnet",
      "adapterId": "solana-devnet"
    },
    {
      "id": "solana-mainnet-beta",
      "label": "Solana Mainnet",
      "family": "solana",
      "stage": "planned",
      "environment": "mainnet"
    },
    {
      "id": "ethereum-sepolia",
      "label": "Ethereum Sepolia",
      "family": "evm",
      "stage": "planned",
      "environment": "testnet",
      "chainId": "11155111"
    },
    {
      "id": "arbitrum-sepolia",
      "label": "Arbitrum Sepolia",
      "family": "evm",
      "stage": "planned",
      "environment": "testnet",
      "chainId": "421614"
    },
    {
      "id": "tempo-testnet",
      "label": "Tempo Testnet",
      "family": "evm",
      "stage": "planned",
      "environment": "testnet"
    },
    {
      "id": "zcash-testnet",
      "label": "Zcash Testnet",
      "family": "utxo",
      "stage": "planned",
      "environment": "testnet"
    },
    {
      "id": "wormhole-integration",
      "label": "Wormhole Integration",
      "family": "bridge",
      "stage": "planned",
      "environment": "integration"
    },
    {
      "id": "hyperliquid-testnet",
      "label": "Hyperliquid Testnet",
      "family": "exchange",
      "stage": "planned",
      "environment": "testnet"
    }
  ]
} as const;
