// Generated by scripts/build-web-runtime-catalog.ts. Do not edit by hand.

export const runtimeCatalog = {
  "generatedFrom": "packages/privatedao-runtime/src/catalog.ts and networks.ts",
  "products": [
    {
      "id": "blind-verification",
      "name": "Blind Verification",
      "availability": "available",
      "networks": [
        "solana-devnet",
        "ethereum-sepolia",
        "tempo-testnet"
      ],
      "capabilities": [
        {
          "id": "verification.blind.prove",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.blind.prove",
              "method": null,
              "note": "Kernel adapter delegates to the HTTPS proof service and accepts only an observed successful public proof package."
            },
            {
              "network": "ethereum-sepolia",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.blind.prove",
              "method": null,
              "note": "Ethereum Sepolia verifier deployment and negative-proof tests are recorded in the EVM testnet evidence packet."
            },
            {
              "network": "tempo-testnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.blind.prove",
              "method": null,
              "note": "Tempo Testnet Groth16 verifier and blind registry passed real on-chain proof, altered-proof, wrong-chain, expiry, and revocation checks."
            }
          ]
        }
      ]
    },
    {
      "id": "record-verification",
      "name": "Record Verification",
      "availability": "available",
      "networks": [
        "solana-devnet",
        "ethereum-sepolia",
        "tempo-testnet"
      ],
      "capabilities": [
        {
          "id": "verification.record.create",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.record.create",
              "method": null,
              "note": "Kernel-native digest and selective disclosure artifact; no public URL or on-chain anchor is created."
            },
            {
              "network": "ethereum-sepolia",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.record.create",
              "method": null,
              "note": "Ethereum Sepolia record registry deployment and transaction evidence are recorded; source payload remains off-chain."
            },
            {
              "network": "tempo-testnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.record.create",
              "method": null,
              "note": "Tempo Testnet record registry passed real on-chain anchoring, verification, expiry, and revocation checks."
            }
          ]
        },
        {
          "id": "verification.record.verify",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.record.verify",
              "method": null,
              "note": "Kernel-native digest verification; no source payload is returned and no on-chain anchor is claimed."
            },
            {
              "network": "ethereum-sepolia",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.record.verify",
              "method": null,
              "note": "Ethereum Sepolia record verification and wrong-network/altered-proof tests are recorded in the EVM evidence packet."
            },
            {
              "network": "tempo-testnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://verification.record.verify",
              "method": null,
              "note": "Tempo Testnet record verification is bound to chain ID 42431 and the deployed registry domain."
            }
          ]
        }
      ]
    },
    {
      "id": "payroll",
      "name": "Confidential Payroll",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "payroll.calculate",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://payroll.calculate",
              "method": null,
              "note": "Kernel-native deterministic calculation; no wallet signature or settlement is performed."
            }
          ]
        },
        {
          "id": "payroll.approve",
          "version": "1.0",
          "requiresSignature": true,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "unbound",
              "entrypoint": null,
              "method": null,
              "note": "Payroll approval state machine is not yet exposed as a Kernel-backed application action."
            }
          ]
        },
        {
          "id": "payroll.settle",
          "version": "1.0",
          "requiresSignature": true,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "legacy-provider",
              "entrypoint": "/api/private-payout/prepare",
              "method": "POST",
              "note": "Existing private-payout provider route; it is not evidence of an end-to-end payroll settlement."
            }
          ]
        }
      ]
    },
    {
      "id": "treasury",
      "name": "Private Treasury",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "treasury.policy.check",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://treasury.policy.check",
              "method": null,
              "note": "Kernel-native deterministic policy evaluation; no wallet signature or treasury movement is performed."
            }
          ]
        }
      ]
    },
    {
      "id": "governance",
      "name": "Private Governance",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "governance.proposal.execute",
          "version": "1.0",
          "requiresSignature": true,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "unbound",
              "entrypoint": null,
              "method": null,
              "note": "No exact Kernel-backed governance execution action is exposed by the web app."
            }
          ]
        }
      ]
    },
    {
      "id": "auction",
      "name": "Private Auctions",
      "availability": "available",
      "networks": [
        "solana-devnet"
      ],
      "capabilities": [
        {
          "id": "auction.bid.commit",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://auction.bid.commit",
              "method": null,
              "note": "Kernel adapter delegates to the HTTPS sealed-bid commitment service; it returns observed public commitments and does not claim a wallet signature or token movement."
            }
          ]
        },
        {
          "id": "auction.settle",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://auction.settle",
              "method": null,
              "note": "Kernel adapter delegates to the HTTPS outcome-proof service; it proves an already-bound result and does not claim token movement or an on-chain signature."
            }
          ]
        }
      ]
    },
    {
      "id": "agent",
      "name": "Agent Marketplace",
      "availability": "available",
      "networks": [
        "solana-devnet",
        "solana-mainnet-beta"
      ],
      "capabilities": [
        {
          "id": "agent.discover",
          "version": "1.0",
          "requiresSignature": false,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "kernel-gateway",
              "entrypoint": "kernel://agent.discover",
              "method": null,
              "note": "Kernel-native read-only Agent Card fetch; no agent activity or external adoption is inferred."
            },
            {
              "network": "solana-mainnet-beta",
              "mode": "legacy-provider",
              "entrypoint": "/api/discovery",
              "method": "GET",
              "note": "Live Agent Exchange discovery surface; evidence is runtime HTTP discovery, not external adoption or a Kernel execution claim."
            }
          ]
        },
        {
          "id": "agent.invoke",
          "version": "1.0",
          "requiresSignature": true,
          "supportsAsync": true,
          "receiptSchema": "privatedao.execution-receipt.v1",
          "applicationBindings": [
            {
              "network": "solana-devnet",
              "mode": "unbound",
              "entrypoint": null,
              "method": null,
              "note": "No Kernel-backed Agent Marketplace invocation action is exposed by the web app."
            },
            {
              "network": "solana-mainnet-beta",
              "mode": "legacy-provider",
              "entrypoint": "/api/jobs",
              "method": "POST",
              "note": "Live Agent Exchange job surface; free invocation and payment-intent generation are observed, while paid settlement remains unverified."
            }
          ]
        }
      ]
    }
  ],
  "networks": [
    {
      "id": "solana-devnet",
      "label": "Solana Devnet",
      "family": "solana",
      "stage": "available",
      "environment": "devnet",
      "adapterId": "solana-devnet"
    },
    {
      "id": "solana-mainnet-beta",
      "label": "Solana Mainnet",
      "family": "solana",
      "stage": "available",
      "environment": "mainnet",
      "adapterId": "solana-mainnet-beta"
    },
    {
      "id": "ethereum-sepolia",
      "label": "Ethereum Sepolia",
      "family": "evm",
      "stage": "available",
      "environment": "testnet",
      "chainId": "11155111",
      "adapterId": "evm-ethereum-sepolia"
    },
    {
      "id": "ethereum-mainnet",
      "label": "Ethereum Mainnet",
      "family": "evm",
      "stage": "planned",
      "environment": "mainnet",
      "chainId": "1",
      "adapterId": "evm"
    },
    {
      "id": "arbitrum-sepolia",
      "label": "Arbitrum Sepolia",
      "family": "evm",
      "stage": "planned",
      "environment": "testnet",
      "chainId": "421614",
      "adapterId": "evm"
    },
    {
      "id": "arbitrum-one",
      "label": "Arbitrum One",
      "family": "evm",
      "stage": "planned",
      "environment": "mainnet",
      "chainId": "42161",
      "adapterId": "evm"
    },
    {
      "id": "bnb-testnet",
      "label": "BNB Smart Chain Testnet",
      "family": "evm",
      "stage": "planned",
      "environment": "testnet",
      "chainId": "97",
      "adapterId": "evm"
    },
    {
      "id": "bnb-mainnet",
      "label": "BNB Smart Chain",
      "family": "evm",
      "stage": "planned",
      "environment": "mainnet",
      "chainId": "56",
      "adapterId": "evm"
    },
    {
      "id": "base-sepolia",
      "label": "Base Sepolia",
      "family": "evm",
      "stage": "planned",
      "environment": "testnet",
      "chainId": "84532",
      "adapterId": "evm"
    },
    {
      "id": "base-mainnet",
      "label": "Base Mainnet",
      "family": "evm",
      "stage": "planned",
      "environment": "mainnet",
      "chainId": "8453",
      "adapterId": "evm"
    },
    {
      "id": "robinhood-testnet",
      "label": "Robinhood Chain Testnet",
      "family": "evm",
      "stage": "planned",
      "environment": "testnet",
      "chainId": "46630",
      "adapterId": "evm"
    },
    {
      "id": "robinhood-mainnet",
      "label": "Robinhood Chain",
      "family": "evm",
      "stage": "planned",
      "environment": "mainnet",
      "chainId": "4663",
      "adapterId": "evm"
    },
    {
      "id": "tempo-testnet",
      "label": "Tempo Testnet",
      "family": "evm",
      "stage": "available",
      "environment": "testnet",
      "chainId": "42431",
      "adapterId": "evm-tempo-testnet"
    },
    {
      "id": "tempo-mainnet",
      "label": "Tempo Mainnet",
      "family": "evm",
      "stage": "planned",
      "environment": "mainnet",
      "adapterId": "evm"
    },
    {
      "id": "zcash-testnet",
      "label": "Zcash Testnet",
      "family": "utxo",
      "stage": "planned",
      "environment": "testnet"
    },
    {
      "id": "hyperliquid-testnet",
      "label": "Hyperliquid Testnet",
      "family": "exchange",
      "stage": "planned",
      "environment": "testnet"
    }
  ]
} as const;
