import { supportedLocales } from "@/lib/i18n";

export const siteName = "PrivateDAO";
export const siteTitle = "PrivateDAO - Private Decisions. Verifiable Outcomes.";
export const siteDescription =
  "PrivateDAO helps organizations prove workflows, make private decisions, and coordinate treasury approvals without exposing sensitive data.";
export const siteUrl = process.env.NEXT_PUBLIC_LIVE_SITE_URL?.replace(/\/+$/, "") ?? "https://privatedao.org";
export const defaultOgImage = `${siteUrl}/opengraph-image.png?v=20260618-commercial`;

export const siteKeywords = [
  "PrivateDAO",
  "Private DAO",
  "PrivateDAO workflow",
  "PrivateDAO Stack",
  "PrivateDAO AI guide",
  "PrivateDAO evidence manifest",
  "proof workflows",
  "private decisions",
  "verifiable outcomes",
  "commercial proof workflow",
  "credit decision verification",
  "audit-ready workflow",
  "private governance",
  "treasury coordination",
  "confidential governance OS",
  "confidential coordination infrastructure",
  "PrivateDAO Solana",
  "PrivateDAO private rooms",
  "PrivateDAO public DAO",
  "confidential governance",
  "encrypted treasury coordination",
  "organizational infrastructure",
  "post-governance operating system",
  "private coordination layer",
  "organizational workflow engine",
  "reviews and approvals",
  "review committees",
  "grant reviews",
  "vendor reviews",
  "investment reviews",
  "proof center",
  "process integrity",
  "public verification",
  "transparency report",
  "asset context",
  "token risk context",
  "price context",
  "confidential vesting",
  "private governance",
  "private DAO governance",
  "private room DAO",
  "public DAO private voting",
  "confidential treasury",
  "confidential treasury request",
  "treasury policy",
  "encrypted payments",
  "confidential payroll",
  "encrypted payroll",
  "private payroll",
  "GamingDAO",
  "gaming DAO rewards",
  "Android Solana app",
  "sovereign intelligence",
  "decision intelligence",
  "AI decision support",
  "wallet-first execution",
  "Solana app",
  "Solana governance",
  "Solana private voting",
  "Solana wallet connect",
  "Solana wallet QR",
  "Solana private room",
  "Solana Android app",
  "Solana encrypted payments",
  "Solana confidential payroll",
  "Solana private governance",
  "private voting",
  "Solana governance",
  "Solana treasury",
  "Solana DAO infrastructure",
  "DAO treasury infrastructure",
  "Solana operational infrastructure",
  "Solana production readiness",
  "Solana production readiness",
  "Solana RPC services",
  "Solana read node",
  "QuickNode Streams",
  "Solana RPC services",
  "readiness aggregate",
  "backend telemetry",
  "runtime telemetry",
  "proof freshness",
  "API health",
  "AWS read node",
  "Supabase receipts",
  "Covalent data intelligence",
  "on-chain verification",
  "ZK verifier",
  "Squads multisig",
  "timelock enforcement",
  "Token-2022",
  "Anchor 1",
  "QVAC",
  "MagicBlock",
  "GoldRush",
  "Covalent GoldRush",
  "IKA",
  "Umbra",
  "Cloak",
  "Torque",
  "Solana Mobile",
  "REFHE",
  "ZK",
  "Hosted reads",
  "حوكمة خاصة",
  "تصويت خاص",
  "خزينة مشفرة",
  "رواتب مشفرة",
  "برايفيت داو",
  "داو خاص على سولانا",
  "частное управление DAO",
  "конфиденциальное голосование",
  "приватне голосування DAO",
  "gobernanza privada DAO",
  "tesoreria confidencial DAO",
  "governance privata DAO",
  "confidential DAO payroll",
];

export function buildOrganizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: siteName,
    alternateName: ["Private DAO"],
    url: siteUrl,
    logo: `${siteUrl}/assets/logo.png`,
    sameAs: [
      "https://github.com/X-PACT/PrivateDAO",
      "https://www.youtube.com/@privatedao",
      "https://discord.gg/GjJykUtTTt",
      "https://discord.gg/dpD5c7Gfcc",
      "https://discord.gg/PRcD9nFeVf",
      "https://arena.colosseum.org/projects/explore/praivatedao",
      "https://superteam.fun/earn/t/Private-dao-1",
      "https://x.com/privateDAOOS",
      "https://t.me/privateDAOOS",
      "https://t.me/PrivateDAOO",
      "https://t.me/Fahdkotb",
    ],
  };
}

export function buildWebSiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: siteName,
    alternateName: ["Private DAO"],
    url: siteUrl,
    inLanguage: supportedLocales.map((locale) => locale.code),
    keywords: siteKeywords,
    potentialAction: {
      "@type": "SearchAction",
      target: `${siteUrl}/search/?q={search_term_string}`,
      "query-input": "required name=search_term_string",
    },
  };
}

export function buildSoftwareApplicationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: siteName,
    alternateName: ["Private DAO", "PrivateDAO Solana"],
    url: siteUrl,
    codeRepository: "https://github.com/X-PACT/PrivateDAO",
    applicationCategory: "Organizational Workflow Verification Software",
    operatingSystem: "Web, Android",
    description:
      "PrivateDAO helps organizations make private decisions, coordinate treasury actions, and prove operational workflows without exposing sensitive data.",
    copyrightYear: 2026,
    copyrightHolder: {
      "@type": "Person",
      name: "Fahd Kotb / Eslam Kotb",
    },
    creator: {
      "@type": "Person",
      name: "Fahd Kotb",
    },
    maintainer: {
      "@type": "Organization",
      name: "X-PACT",
      url: "https://github.com/X-PACT",
    },
    license: "https://github.com/X-PACT/PrivateDAO/blob/main/LICENSE",
    keywords: siteKeywords.join(", "),
    softwareHelp: `${siteUrl}/learn/`,
    downloadUrl: `${siteUrl}/android/`,
    featureList: [
      "Proof Workflows for underwriting, compliance, reviews, approvals, and audits",
      "Private Governance for rooms, voting, committees, and organizational decisions",
      "Treasury Coordination for requests, approvals, treasury-token workflows, and audit trails",
      "Wallet-first governance where blockchain execution is used",
      "Private commit-reveal voting posture",
      "Proof center and audit records",
      "Advanced confidential payroll, payment, vesting, and settlement modules",
      "Local-first decision intelligence",
      "Solana telemetry and RPC readiness",
      "Reviewer-safe readiness aggregate API",
      "Hosted read-node health and metrics",
      "Supabase-backed operation receipt posture",
      "Reviewer-visible proof and runtime evidence",
      "Standalone ZK verifier receipt",
      "Squads multisig timelock enforcement proof",
      "PDAO Token-2022 fixed-supply governance mint",
    ],
    sameAs: [
      "https://github.com/X-PACT/PrivateDAO",
      "https://x.com/privateDAOOS",
      "https://www.youtube.com/@privatedao",
      "https://discord.gg/GjJykUtTTt",
      "https://discord.gg/dpD5c7Gfcc",
      "https://discord.gg/PRcD9nFeVf",
      "https://arena.colosseum.org/projects/explore/praivatedao",
      "https://superteam.fun/earn/t/Private-dao-1",
      "https://t.me/privateDAOOS",
      "https://t.me/PrivateDAOO",
      "https://t.me/Fahdkotb",
    ],
  };
}
